### ISSUE TITLE
Add a build option to rename all LLVM symbols

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#12644]
A lot of libraries embed some version of LLVM nowadays (e.g. NVIDIA SDKs), which causes a problem when julia uses LLVM as a shared library. It would be great to have a Makefile option that prefixes all LLVM symbols with `jl_` or some such.

**Comment by vtjnash** [comment]
when we link to llvm as a static library, i think we hide all of the symbols (partly because of this issue). when we link dynamically, it is often because we are linking to the system llvm (which we have no control over).

tl;dr i'm not sure this is going to work

**Comment by Keno** [comment]
There is plenty of reasons to use LLVM dynamically other than it being the system LLVM, we even have a Makefile option for it. In particular, it is used for Cxx.jl, so there's a number of people who run julia in this configuration.

**Comment by vtjnash** [comment]
Can we use `dlopen(RTLD_LOCAL)` and get the same effect, without the complications from doing renaming?

**Comment by tkelman** [comment]
codegen isn't dlopen'ing shared llvm, it's using normal linking

**Comment by yuyichao** [comment]
Would be nice if llvm has a namespace compile time option (like Qt).

**Comment by vchuravy** [comment]
We recently gotten a multitude of reports about this https://github.com/JuliaGPU/OpenCL.jl/issues/125#issuecomment-268078204 and https://discourse.julialang.org/t/llvm-problem-with-running-glfw-jl/1110 so it would be nice if we could work around this in Julia.

**Comment by stevengj** [comment]
I'm getting reports of [this happening with PyPlot](https://discourse.julialang.org/t/unable-to-plot-from-the-repl-with-pyplot/3112/9?u=stevengj), too; apparently some Matplotlib backends link LLVM.

**Comment by ihnorton** [comment]
LLVM upstream has added `--default-symver` for this reason: https://reviews.llvm.org/D30997

**Comment by ihnorton** [comment]
If anyone is dealing with this right now, for the short term: try `dlopen`ing the other LLVM-using library with `Libdl.RTLD_DEEPBIND` (but make sure you do it as the **very first** dlopen of a given library path -- the first load options dominate).

**Comment by dehann** [comment]
Hi All, I'm trying to install `Clang.jl` and ended up here too. Hope this adds value, and figured `Clang.jl` has a large impact on the Julia ecosystem. (Note this happens both w/ or wo/ `Cxx.jl` installed):
```julia
julia> Pkg.add("Clang")
...
LoadError: No useable llvm-config found
while loading /home/dehann/.julia/v0.6/Clang/deps/build.jl, in expression starting on line 64
...
```
Adding a system install ```sudo apt-get install llvm``` changes the behavior to:
```julia
INFO: Building Clang
INFO: Called Clang.jl:find_llvm
g++ wrapclang.cpp -fPIC -c -o wrapclang.cpp.o -I/usr/lib/llvm-3.4/include -g -I/usr/lib/llvm-3.4/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fPIC 
wrapclang.cpp:7:27: fatal error: clang-c/Index.h: No such file or directory
 #include "clang-c/Index.h"
                           ^
compilation terminated.
make: *** [wrapclang.cpp.o] Error 1
=======================================================================================[ ERROR: Clang ]========================================================================================

LoadError: clang headers could not be found and BUILD_LLVM_CLANG=1 not specified in Make.user
Try setting BUILD_LLVM_CLANG=1 in Make.user in /home/dehann/software/julia-0d7248e2ff/bin and try again.
while loading /home/dehann/.julia/v0.6/Clang/deps/build.jl, in expression starting on line 90
```
Setup is `Ubuntu 16.04` or `14.04`, and binary install of both `Julia 0.6.0` and `0.6.1`.

Thanks for the great work!

**Comment by GeraldKaeferle** [comment]
@dehann: try  `sudo apt-get install llvm-dev clang-dev`. I t worked for me in Fedora with `sudo dnf install llvm-dev clang-dev`.

**Comment by stevengj** [comment]
I've gotten a couple of reports of segfaults when loading Python libraries for the same reason … a lot of things seem to be pulling in LLVM these days.

Any chance we can compile LLVM with `--default-symver` sometime soon?

**Comment by dehann** [comment]
@GeraldKaeferle : thanks, sorry for slow reply -- on Ubuntu 16.04 the packages were `llvm-dev` and `libclang-dev`.  With Julia 1.0, I was then able to add `Clang` and the tests pass.  Thanks.

**Comment by stevengj** [comment]
@banex19, is this fixed by https://github.com/JuliaLang/julia/blob/master/deps/patches/llvm7-symver-jlprefix.patch (#31508) since that uses `JL_LLVM_<major>_<minor>` for symbol versioning?

**Comment by Orbots** [comment]
I've run into an issue recently where symver doesn't appear to help.  #32616  I don't really understand DSO symbol resolution complications, they are  counter-intuitive for someone used to the sanity of lexical scoping.

The conflicting lib did a reasonable thing and appear to have effectively done a find and replace for `namespace llvm` with their own custom namespace.  This hides most of llvm's symbols from other llvm users.  But not all of them.
 
```
} // end namespace llvm

extern "C" void LLVMInitializeX86Target() {
```

If you were to prefix anything in LLVM with jl_  I'd propose that some of these un-namespaced extern "C" procedures should be considered.

**Comment by ihnorton** [comment]
It looks like LLVM now does symbol versioning by default with a linker script:
https://github.com/llvm-mirror/llvm/blob/9070b54da16dfbd2f93be617aa42c06093678adb/tools/llvm-shlib/CMakeLists.txt#L55-L57

but that may not be sufficient, as it seems a number of projects are still encountering this issue (in both the Julia and Python ecosystems). I wonder if projects need to override that linker script and make the SOVERSION something like `llvm_major.llvm_minor.julia` so that symbols are unique even when the version numbers are the same.

**Comment by vchuravy** [comment]
Yeah some of the remaining issues are caused by the usage of weaksymbols iirc in libclang, and maybe dlsym

**Comment by tkf** [comment]
What is the timeline to switch to use LLVM 7 by default, especially in the binary distributions?

**Comment by vchuravy** [comment]
As soon as someone manages to debug the windows failure we see on the LLVM
8.0.1 branch. https://github.com/JuliaLang/julia/pull/32712

**Comment by Orbots** [comment]
For a really solid solution, renaming LLVM symbols appears to be most fool-proof solution.
If an unversioned set of llvm symbols has been loaded into a program before julia, then symbol versioning will not fix the problems.  

If you have full control over what shared libraries are loaded or the order they are loaded in you can work around this.  If you can't, then you have a fragile situation.

**Comment by stevengj** [comment]
People are now reporting potentially related issues with numba's LLVM (loaded via PyCall): JuliaPy/PyCall.jl#903

**Comment by vtjnash** [comment]
Julia uses an LLVM with symbol versioning enabled now. Other projects may still need to update to avoid problems however. But we can't control that.

**Comment by vtjnash** [comment]
And note that the fix may depend on projects using dlsym correctly, and specifying the correct library target (as is also required for supporting Windows, and sometimes macOS too).

**Comment by moble** [comment]
@vtjnash Can you be more specific about how dlsym may be used incorrectly?  I can verify that https://github.com/JuliaPy/PyCall.jl/issues/903 that @stevengj pointed to is still a problem, along with JuliaPy/pyjulia#443, which appear to be similar to cjdoris/PythonCall.jl#115.  At least this is true on macOS with all the latest versions of everything — though at least some of these problems are apparently resolved on other platforms.

**Comment by vtjnash** [comment]
Seems from those issues that this is a numba issue. They might be missing a library name to one of their ffi (ctypes.py) calls.

**Comment by vtjnash** [comment]
In trivial cases, the first argument to dlsym can be omitted, but not if you want to be reliable or to support all platforms

**Comment by moble** [comment]
It is coming from the python side.  The situation is affected by how the python packages are built and linked.  Unfortunately, packages installed from conda-forge (where most people will get it) isn't being built and linked in the right ways.  It looks like this would also be a problem for pytorch — and presumably any other conda package using LLVM.  FWIW, installing numba from the numba conda channel, or via pip, does work.  Anyway, thanks for the pointers.
