### ISSUE TITLE
Regression for loading a datafile

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/julia#13137]
I'm trying to `include` a file and I'm seeing a regression from Julia 0.3.11 to Julia 0.4.0-rc1.

The file is structured as follows:

```jl
z = [0.10820704922407676 0.4818519145226865 0.3383662587000038 0.029596542825756966 0.3521436855741502
 0.24645951793417598 0.20234938073034936 0.4920731002590304 0.38549121070279213 0.8724222229492178
 0.7054929809164956 0.45865980451409216 0.1781556340766206 0.16471993628757087 0.982182007730946
 0.7822204103905868 0.6652624107186051 0.30298838323533284 0.3494632508810176 0.8565539428444622]
```

and whenever the matrix is larger than some boundary value, the call fails with the error

```jl
julia> include("testdata.jl")
ERROR: LoadError: OverflowError()
 in include at boot.jl:260
 in include_from_node1 at loading.jl:271
while loading C:\Users\Tomas Lycken\AppData\Local\Julia-0.4.0-rc1\testdata.jl, in expression starting on line 1
```

This is independent on whether I decrease the number of rows or columns - I've tried both my original file with 200 columns (which fails for 41 rows, but not for 40) and a changed one with 37 columns (which fails for 42 rows, but not for 41).

It does not seem to relate either to the exact number of elements, however; I cannot construct a 41x200 matrix without the error, but 4100x2 and 2x4100 is fine.

To reproduce locally, simply run

```
julia> A = rand(41,200);
julia> open("testfile.jl", "w") do f
           print(f, "z = ")
           print(f, A)
       end
julia> include("testfile.jl")
```

To reproduce without the error, just comment any one line in `testfile.jl` (if you remove the first or last line, be sure to retain `z = [` and `]`).

This was first posted as [a question on julia-users](https://groups.google.com/forum/#!topic/julia-users/NNxOmwzer9Q)

**Comment by tlycken** [comment]
This is what's currently holding me up from fixing tlycken/Contour.jl#18, for reference of an actual use case.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/11884 and https://github.com/JuliaLang/julia/issues/11320. Fixed by https://github.com/JuliaLang/julia/pull/11888

**Comment by tlycken** [comment]
Thanks for the pointers, @yuyichao.

I tried working around this by splitting the matrix literal in chunks, and `vcat`-ting them. This solved the problem locally - I can now run `Pkg.test("Contour")` on both 0.3.11 and 0.4.0-rc1 without errors, but it [still fails on Travis](https://travis-ci.org/tlycken/Contour.jl/jobs/80423121). Any idea how to further work around the problem on Travis as well?

**Comment by JeffBezanson** [comment]
Please try again with the latest master or release-0.4; should be fixed there.
