### ISSUE TITLE
Reshape/tuple issue on 0.6.3 and 0.7, only when in function (compiled?)

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#27617]
Repro:

```
function foo()
    # Create 0D array (scalar).
    z = zeros(())
    old_size = size(z)
    # Confirm it is indeed a scalar.
    @show z, old_size
    # Create tuple in kind of odd way, should be (1,).
    new_size = tuple(old_size[1:0]..., 1, old_size[1:end]...)
    @show new_size, typeof(new_size)
    @show new_size === (1,)
    # Atttempt to reshape.
    g = reshape(z, new_size)
    # It kind of works? Prints as [0.0], but size/type still 0D.
    @show g, size(g), typeof(g)
    @assert size(g) == ()
    # Make it manually.
    new_size = (1,)
    @show new_size, typeof(new_size)
    @show new_size === (1,)
    # Now it works!
    @show g, size(g), typeof(g)
    g = reshape(z, new_size)
    @show g, size(g), typeof(g)
    @assert size(g) == (1,)
end
foo()
```

If one drops the function and runs in global scope, the first case works as it should (and the assert will start failing).

```
julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc350 (2018-05-28 20:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by KristofferC** [comment]
On 0.7 I get:

```
(z, old_size) = (0.0, ())
(new_size, typeof(new_size)) = ((1,), Tuple{Int64})
new_size === (1,) = true
(g, size(g), typeof(g)) = ([0.0], (1,), Array{Float64,1})
test set: Error During Test at REPL[2]:1
  Got exception AssertionError("size(g) == ()") outside of a @test
  AssertionError: size(g) == ()
```

**Comment by IainNZ** [comment]
Ah maybe its been fixed with all the other changes!

**Comment by IainNZ** [comment]
Since it only occurs on 0.6.3, is there any use keeping this open?

**Comment by KristofferC** [comment]
Probably not, arguably adding a test would be good so it doesn't regress.

**Comment by IainNZ** [comment]
Sounds reasonable. Any suggestions for where? I'm not even sure what is happening in this bug, or how being in a testset should affect behaviour like this (!)

**Comment by KristofferC** [comment]
The fact that it was in a testset might have meant that it was being compiled instead of interpreted. Putting it in a function might achieve the same effect as the test set. In fact, even on 0.7, when I put this in a function, it doesn't assert so perhaps this isn't fixed after all.

**Comment by IainNZ** [comment]
@vtjnash this might be some sort of compiler bug

**Comment by IainNZ** [comment]
Confirmed putting in function also achieves same purpose on 0.6.3.

**Comment by vtjnash** [comment]
Reduction to subtyping bug - probably the same as #27632:
```
julia> methods(reshape, (Array{Float64,0}, Tuple{Vararg{Int64,N} where N}), )
# 1 method for generic function "reshape":
[1] reshape(a::Array{T,N}, dims::Tuple{Vararg{Int64,N}}) where {N, T} in Base at array.jl:278

julia> methods(reshape, (Array{Float64,1}, Tuple{Vararg{Int64,N} where N}), )
# 2 methods for generic function "reshape":
[1] reshape(a::Array{T,N}, dims::Tuple{Vararg{Int64,N}}) where {N, T} in Base at array.jl:278
[2] reshape(a::Array{T,N} where N, dims::Tuple{Vararg{Int64,N}}) where {N, T} in Base at array.jl:289
```
