### ISSUE TITLE
PDF docs deployment broken

### ISSUE THREAD

**Issue by cdluminate** [JuliaLang/julia#33968]
The PDF document is invalid:

https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.3.0.pdf

and the link is found here:

https://docs.julialang.org/en/v1.3/

**Comment by aerdely** [comment]
Still broken as of today 😕

**Comment by ViralBShah** [comment]
Would be nice to fix this. I am happy to do it, if there's instructions I can follow somewhere.

**Comment by espectalll** [comment]
The build script should be the one at [julialang/docs.julialang.org](https://github.com/julialang/docs.julialang.org/). To run it (you might have to install dependencies like PDFLaTeX or Docker, I haven't figured that out), you have to do something like:

```sh
git clone https://github.com/JuliaLang/docs.julialang.org
git clone https://github.com/JuliaLang/julia
cd docs.julialang.org/pdf
JULIA_SOURCE=../../julia julia make.jl releases
```

I decided to modify the `make.jl` script with my own small patches, to save myself some time and effort, adding a `#!/usr/bin/env julia` header and rewriting the following function:

```julia
function collect_versions()
    versions = VersionNumber[]
    push!(versions, v"1.3.0")
    return versions
end
```

...and I got this error

```
┌ Error: LaTeXWriter: failed to compile tex with docker. Logs and partial output can be found in /tmp/jl_yokbBF.
│   exception =
│    failed process: Process(`docker exec -u zeptodoctor latex-container bash -c 'mkdir /home/zeptodoctor/build
│    cd /home/zeptodoctor/build
│    cp -r /mnt/. .
│    latexmk -f -interaction=nonstopmode -view=none -lualatex -shell-escape TheJuliaLanguage.tex
│    '`, ProcessExited(12)) [12]
│    
└ @ Documenter.Writers.LaTeXWriter ~/Projects/julia/doc/deps/packages/Documenter/cMNJA/src/Writers/LaTeXWriter.jl:173
```

**Comment by espectalll** [comment]
(keep in mind: I keep my Julia repo at `~/Projects/julia`, and I couldn't find that `/tmp/jl_yokbBF` anywhere)

**Comment by fredrikekre** [comment]
This is the real issue: https://github.com/JuliaDocs/Documenter.jl/issues/1200

**Comment by aerdely** [comment]
The problem has been fixed!

**Comment by StefanKarpinski** [comment]
It was fixed manually, we should still track the upstream issue to make sure the PDF is automatically generated in the future.

**Comment by ViralBShah** [comment]
Inside the pdf, it says the manual is for 1.3.0-alpha. Not sure if it is the right manual with an incorrect version, or if it is an older manual.

**Comment by fredrikekre** [comment]
It's an older manual.

**Comment by ViralBShah** [comment]
Should we remove the pdf link from the manual until this gets fixed?

**Comment by knuesel** [comment]
The link on `https://docs.julialang.org/en/v1/` is still broken.

**Comment by fredrikekre** [comment]
No, it just broke due to 1.4.1. PDFs are generated once a day so it will be up tomorrow.

**Comment by ViralBShah** [comment]
I had no idea the pdf docs were so popular!
