### ISSUE TITLE
Julia 1.7 does not start on macOS Monterey

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#42875]
I have just updated my Mac to Monterey and Julia 1.7 won’t start anymore. Calling it in the terminal gives

```
fatal: error thrown and no exception handler available.
InitError(mod=:Sys, error=ErrorException("PCRE compilation error: unrecognised compile-time option bit(s) at offset 0"))
error at ./error.jl:33
compile at ./pcre.jl:155
compile at ./regex.jl:82
#occursin#442 at ./regex.jl:265 [inlined]
occursin at ./regex.jl:265 [inlined]
isdirpath at ./path.jl:117 [inlined]
normpath at ./path.jl:369
abspath at ./path.jl:426
abspath at ./path.jl:435 [inlined]
__init_build at ./sysinfo.jl:125
__init__ at ./sysinfo.jl:117
jfptr___init___27501.clone_1 at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_module_run_initializer at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_finish_julia_init at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
julia_init at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
```
Julia 1.6 still works without problem.

original issue on discourse: https://discourse.julialang.org/t/cannot-start-julia-1-7-rc2/70629

another issue discussing the same problem:
https://discourse.julialang.org/t/is-julia-compatible-with-mac-os-monterey/70588/12

Just for reference, I have Xcode version 13.1 and Perl version 5.30.3, and Intel x86

**Comment by mgkuhn** [comment]
Can you confirm with
```
$ DYLD_PRINT_LIBRARIES=YES julia -e0 2>&1 | grep pcre
```
which PCRE library gets loaded? Just in case the root cause is similar to that fixed by https://github.com/JuliaLang/julia/commit/1385b50c5f9437bcc3460d78a19132215ed895b4 (namely that under Monterey the system library is loaded instead of the one packaged with Julia).

**Comment by matthieugomez** [comment]
Thanks for your help. I get
```

→DYLD_PRINT_LIBRARIES=YES
/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia -e0 2>&1 |
grep pcre     15:03
dyld[44331]: <33D0E13B-557D-3C47-A894-BC062F3BF6EA>
/usr/local/Cellar/pcre2/10.33/lib/libpcre2-8.0.dylib
compile at ./pcre.jl:155
```

With Julia 1.6 I get
```

→DYLD_PRINT_LIBRARIES=YES
/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -e0 2>&1 |
grep pcre     15:03
dyld[44251]: <20CE2416-6B33-313F-8B31-1956C0289A2D>
/Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libpcre2-8.0.dylib
```

**Comment by mgkuhn** [comment]
This looks indeed much like the problem that #42721 is meant to fix, which has already been merged into master and has been [back-ported to 1.7-rc3](https://github.com/JuliaLang/julia/pull/42765). Does the current "Nightly" build still have this problem?

**Comment by matthieugomez** [comment]
I just downloaded the nightly build but it still does not work. I get the
same message as with 1.7. Moreover, your command returns the same thing too:
```julia
→DYLD_PRINT_LIBRARIES=YES
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -e0 2>&1 |
grep pcre     15:04
dyld[45168]: <33D0E13B-557D-3C47-A894-BC062F3BF6EA>
/usr/local/Cellar/pcre2/10.33/lib/libpcre2-8.0.dylib
compile at ./pcre.jl:155
```

**Comment by KristofferC** [comment]
What commit is that build on?

**Comment by matthieugomez** [comment]
The release called “nightly release” currently on the Julia webpage. Not
sure which commit it corresponds to since Julia never display the startup
message.

**Comment by IanButterworth** [comment]
You could try
```
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -e "println(Base.GIT_VERSION_INFO.commit_short)"
```
or
```
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia -e "println(VERSION)"
```

**Comment by vchuravy** [comment]
Or `cat /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/base/version_git.jl`

**Comment by matthieugomez** [comment]
Thanks, I get
```
→cat
/Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/base/version_git.jl
                        19:05
const GIT_VERSION_INFO = GitVersionInfo(
    "86f656d414463ed20b28aa6138dc3e3917b77a84",
    "86f656d414",
    "master",
    849,
    "2021-10-31 12:23 UTC",
    false,
    0,
    1635682986.
)
```

**Comment by IanButterworth** [comment]
Looks like that includes https://github.com/JuliaLang/julia/pull/42721

For the record I'm on Monterey and 1.6.3 1.7.0-rc2 and master all work

**Comment by mgkuhn** [comment]
@IanButterworth You may not have done a `brew install pcre2` (or installed something with that dependency), and therefore wouldn't have a file `/usr/local/Cellar/pcre2/10.*/lib/libpcre2-8.0.dylib` in place, which appears to be accidentally loaded here.

Also: in any report about macOS Big Sur or newer, please always state now the architecture (Intel or ARM), as these can behave quite differently, and almost certainly involve many different OS code paths and bugs^Wundocumented behaviours.

**Comment by ararslan** [comment]
As a data point, the official Julia v1.7.0-rc2 binary starts for me on macOS Monterey with an Intel processor but it loads a bunch of stuff from Homebrew, not limited to PCRE:
```
$ DYLD_PRINT_LIBRARIES=YES julia-1.7 -e0 2>&1 | grep Cellar
dyld[55733]: <0EB97527-8062-3980-9B57-FFFE77865366> /usr/local/Cellar/pcre2/10.39/lib/libpcre2-8.0.dylib
dyld[55733]: <4B4F7550-52BB-3A84-8EA0-E185D1B0AD96> /usr/local/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib
dyld[55733]: <9719A42C-62D4-3FC3-8126-71D0E9F28286> /usr/local/Cellar/mpfr/4.1.0/lib/libmpfr.6.dylib
dyld[55733]: <9E6F89CD-80B1-3854-BBB1-7EF298248E20> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcholmod.3.0.14.dylib
dyld[55733]: <E337A34E-03BA-398C-9D8B-9A49383A4217> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libamd.2.4.6.dylib
dyld[55733]: <0194750F-E9FD-3046-9A2D-8306543DA7E6> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcolamd.2.9.6.dylib
dyld[55733]: <6910998D-E947-3727-BC82-062609A55845> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libsuitesparseconfig.5.10.1.dylib
dyld[55733]: <D5EBC481-E1D8-3B2D-BE75-DE7D97917461> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libccolamd.2.9.6.dylib
dyld[55733]: <8E53F9CD-9F73-37B3-9861-95305837BEA5> /usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcamd.2.4.6.dylib
dyld[55733]: <0D6A13B3-0000-3A1B-9D4B-FE7FC26EB080> /usr/local/Cellar/metis/5.1.0/lib/libmetis.dylib
dyld[55733]: <771D9013-16D5-398D-A574-E25668082EC3> /usr/local/Cellar/openblas/0.3.18/lib/libopenblasp-r0.3.18.dylib
dyld[55733]: <AA03350C-65CB-38B4-BEB3-F6E285AB679E> /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgfortran.5.dylib
dyld[55733]: <439E9195-9185-3FE0-B9DE-D588A6B5BC38> /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgomp.1.dylib
dyld[55733]: <5AB791C6-291D-348A-B671-F75912B6B410> /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib
dyld[55733]: <586B895A-9FF1-38DC-BEFC-6B403B4492C3> /usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgcc_s.1.dylib
dyld[55733]: <9DC0DFEE-819A-36A7-B4C2-530DD3091095> /usr/local/Cellar/libnghttp2/1.46.0/lib/libnghttp2.14.dylib
$ julia-1.7 -q
julia> versioninfo()
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by staticfloat** [comment]
I think v1.7.0 needs https://github.com/JuliaLang/julia/pull/42721 backported to fix that issue.  The latest nightly should not have that issue, is that correct Alex?

**Comment by matthieugomez** [comment]
I think that the latest nightly still has this issue — that was what Ian asked me to check.

**Comment by mgkuhn** [comment]
Note that @ararslan has `Cellar/pcre2/10.39` installed whereas @matthieugomez had the much older `Cellar/pcre2/10.33` (April 2019) installed, so could the particular exception reported have to do with Julia 1.7-rc2 finding a too-old PCRE2 installation? Both Julia master and release-1.7 [build with PCRE 10.36](https://github.com/JuliaLang/julia/blob/e03ead07e9ce8fdae09dbbc45e891aa93ab03ee5/deps/Versions.make#L99).

Hence a workaround for @matthieugomez could be a simple `brew update; brew upgrade pcre2`, and that could explain others not being able to reproduce the exception, but the *real* problem appears to be that with the current Julia binaries `dyld` looks for libpcre2 at the wrong place.

**Comment by matthieugomez** [comment]
Markus — thanks again for your explanations. Following your advice, I
upgraded brew and I can now start Julia 1.7. As you mention, it still uses
the (updated) libpcre2 library in my brew folder.
```
→DYLD_PRINT_LIBRARIES=YES
/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia -e0 2>&1 |
grep pcre     15:23
dyld[4045]: <0EB97527-8062-3980-9B57-FFFE77865366>
/usr/local/Cellar/pcre2/10.39/lib/libpcre2-8.0.dylib
```

**Comment by ararslan** [comment]
> The latest nightly should not have that issue, is that correct Alex?

The latest nightly still loads a bunch of libraries from Homebrew for me.

**Comment by IanButterworth** [comment]
I assume this is related to picking up the wrong curl lib too?
```
pkg> up
    Updating registry at `~/.julia/registries/General`
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
```

https://github.com/JuliaLang/Pkg.jl/issues/2788#issuecomment-951435228

**Comment by ararslan** [comment]
libcurl is getting loaded from the system for me.

For posterity, Homebrew check for nightly, done within Julia for stupid notarization reasons:
```julia
julia> io = IOBuffer();

julia> withenv("DYLD_PRINT_LIBRARIES" => "YES") do
           run(pipeline(`$(Base.julia_cmd()) -e0`; stdout=io, stderr=io))
       end
Process(`/private/var/folders/dv/q8h35hc9195_3dvwd_rfwpwr0000gn/T/AppTranslocation/8705E378-6920-4193-B382-C302CF9906C9/d/Julia-1.8.app/Contents/Resources/julia/bin/julia -Cnative -J/private/var/folders/dv/q8h35hc9195_3dvwd_rfwpwr0000gn/T/AppTranslocation/8705E378-6920-4193-B382-C302CF9906C9/d/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib -g1 -e0`, ProcessExited(0))

julia> seekstart(io);

julia> [last(split(line, ' ')) for line in eachline(io) if occursin("Cellar", line)]
15-element Vector{SubString{String}}:
 "/usr/local/Cellar/pcre2/10.39/lib/libpcre2-8.0.dylib"
 "/usr/local/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib"
 "/usr/local/Cellar/mpfr/4.1.0/lib/libmpfr.6.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcholmod.3.0.14.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libamd.2.4.6.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcolamd.2.9.6.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libsuitesparseconfig.5.10.1.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libccolamd.2.9.6.dylib"
 "/usr/local/Cellar/suite-sparse/5.10.1_1/lib/libcamd.2.4.6.dylib"
 "/usr/local/Cellar/metis/5.1.0/lib/libmetis.dylib"
 "/usr/local/Cellar/openblas/0.3.18/lib/libopenblasp-r0.3.18.dylib"
 "/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgfortran.5.dylib"
 "/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgomp.1.dylib"
 "/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libquadmath.0.dylib"
 "/usr/local/Cellar/gcc/11.2.0/lib/gcc/11/libgcc_s.1.dylib"
```

**Comment by staticfloat** [comment]
With @IanButterworth's help, I have managed to track this down to a difference in behavior of `dyld` on macOS Monterey; it appears that `dlopen("@loader_path/libfoo.dylib")` always searches `/usr/local/lib`, no matter what `DYLD_FALLBACK_LIBRARY_PATH` is set to.  I've reached out to Apple to see if they have any guidance.

Can someone with problems please start up Julia with `DYLD_PRINT_SEARCHING=1` set?  The central issue should be that it searches a location in the Julia install first, doesn't find the library, then hits a fallback path (that we do not expect to exist), and loads the wrong library.  Temporary workarounds include:

* Remove the offending libraries from the fallback paths, e.g. `brew unlink gmp`, etc...

* Insert the proper libraries into whatever location `dyld` checks first, e.g. `ln -s $julia_prefix/lib/julia/libgmp.dylib $julia_prefix/lib/libgmp.dylib`.  I'm not sure exactly what the paths should be off-hand, that's why I ask for the `DYLD_PRINT_SEARCHING=1` output.

**Comment by ararslan** [comment]
Output from running with `DYLD_PRINT_SEARCHING=1`: https://gist.github.com/ararslan/9e6b80f1931685e39e75f2461f82d347

**Comment by mgkuhn** [comment]
There appears to have been a significant rewrite of `dyld` in macOS 12 an iOS 15:
https://www.emergetools.com/blog/posts/iOS15LaunchTime
I'd be interested to hear if the library-search-path behaviour changes reported here were intentional, or whether Apple considers them a bug and plans a fix.

**Comment by staticfloat** [comment]
@ararslan can you check the latest nightly?  I'm curious as to whether https://github.com/JuliaLang/julia/commit/236523ffc2b0493e8e519a721ec030b7c3a64f83 fixes anything for you.

**Comment by gbaraldi** [comment]
It looks like this isn't an issue with M1 macs because homebrew installs things in `\opt` because I can't reproduce any of the bugs. Even in Rosetta.

**Comment by staticfloat** [comment]
Yes, that's correct; so the default load path of `/usr/local/lib` doesn't interfere at all.

Can anyone test https://s3.amazonaws.com/julialangnightlies/assert_pretesting/mac/x64/1.8/julia-30861bd763-mac64.tar.gz to see if that version starts up for you?

**Comment by IanButterworth** [comment]
https://s3.amazonaws.com/julialangnightlies/assert_pretesting/mac/x64/1.8/julia-30861bd763-mac64.tar.gz
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.885 (2021-11-04)
 _/ |\__'_|_|_|\__'_|  |  refs/pull/42930/merge/30861bd763 (fork: 1 commits, 1 day)
|__/                   |

julia> using Libdl; filter(f -> occursin("gmp", f), Libdl.dllist())
1-element Vector{String}:
 "/Users/ian/Downloads/julia-30861bd763/lib/julia/libgmp.10.dylib"

```

Master
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.887 (2021-11-04)
 _/ |\__'_|_|_|\__'_|  |  Commit 707c57c490 (0 days old master)
|__/                   |

julia> using Libdl; filter(f -> occursin("gmp", f), Libdl.dllist())
1-element Vector{String}:
 "/usr/local/Cellar/gmp/6.2.1/lib/libgmp.10.dylib"

```
Nice work @staticfloat!  🙏🏻

**Comment by staticfloat** [comment]
The latest nightly should now include this fix.  @matthieugomez can you verify?

**Comment by matthieugomez** [comment]
@staticfloat I feel like you're going to kill me but it does not look like it fixes things on my end
 ```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.888 (2021-11-04)
 _/ |\__'_|_|_|\__'_|  |  Commit 8e87263129 (0 days old master)
|__/                   |

julia> using Libdl; filter(f -> occursin("gmp", f), Libdl.dllist())
2-element Vector{String}:
 "/usr/local/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib"
 "/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib"

```

**Comment by aimileus** [comment]
For me it seems this issue is fixed on master:

Julia 1.7rc2:
```
~ $ exec '/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-rc2 (2021-10-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Libdl; filter(f -> occursin("gmp", f), Libdl.dllist())
2-element Vector{String}:
 "/usr/local/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib"
 "/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib"
```

Julia master (4304c51f96):
```
~ $ exec '/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.907 (2021-11-07)
 _/ |\__'_|_|_|\__'_|  |  Commit 4304c51f96 (0 days old master)
|__/                   |

julia> using Libdl; filter(f -> occursin("gmp", f), Libdl.dllist())
1-element Vector{String}:
 "/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib"
```

This is on Moneterey (ARM) running both versions under Rosetta 2, with the offending library installed in `/usr/local/lib`.

**Comment by ararslan** [comment]
Yeah, the situation seems to have been fixed on master, we're now awaiting the corresponding PRs to be backported so that the next versions of 1.6 and 1.7 will work on Monterey as well.
