### ISSUE TITLE
macOS deadlock race when `TERM` != `xterm`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#45118]
On latest master, on my M1 mac machine, we get a racey deadlock when running [this line](https://github.com/JuliaLang/julia/blob/9320fba641e1b78c5b596f4a4a8ad20deb2dfdaa/base/ttyhascolor.jl#L12) which calls `tput` to determine our TTY colorability.

Attaching `lldb`, we see the following backtrace.  Note that this backtrace uses `-t 2` to illustrate the deadlock between multiple tasks, however the issue is actually more reliably triggered with `-t 1`:

```
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x0000000188452c40 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x00000001011ec5ec libjulia-internal.1.9.dylib`uv__io_poll + 1420
    frame #2: 0x00000001011d1130 libjulia-internal.1.9.dylib`uv_run + 192
    frame #3: 0x00000001011694fc libjulia-internal.1.9.dylib`ijl_task_get_next(trypoptask=0x0000000118bce9e0, q=0x0000000108af60f0, checkempty=0x0000000119608f10) at partr.c:385:30 [opt]
    frame #4: 0x0000000117432008 sys.dylib`julia_poptask_25670 at task.jl:935
    frame #5: 0x0000000117432118 sys.dylib`julia_wait_47901 at task.jl:944
    frame #6: 0x00000001174322b4 sys.dylib`julia_wait_47878 at condition.jl:124
    frame #7: 0x00000001176a73f0 sys.dylib`julia_wait_47870 at process.jl:658
    frame #8: 0x00000001172b6830 sys.dylib`julia_success_31151 at process.jl:520
    frame #9: 0x00000001172b63b0 sys.dylib`julia_ttyhascolor_45420 at process.jl:533
    frame #10: 0x00000001172b72e0 sys.dylib`julia_get_45135 at ttyhascolor.jl:7
    frame #11: 0x00000001172b739c sys.dylib`jfptr_get_45136 + 24
    frame #12: 0x0000000101121e54 libjulia-internal.1.9.dylib`ijl_apply_generic [inlined] _jl_invoke(F=0x0000000117f34a20, args=0x000000016f3b3d58, nargs=3, mfunc=0x000000011b5eade0, world=<unavail
able>) at gf.c:0 [opt]
    frame #13: 0x0000000101121dec libjulia-internal.1.9.dylib`ijl_apply_generic(F=0x0000000117f34a20, args=0x000000016f3b3d58, nargs=<unavailable>) at gf.c:2574:12 [opt]
    frame #14: 0x00000001178c8f6c sys.dylib`julia_get_45139 at Terminals.jl:161
    frame #15: 0x00000001178d3ea4 sys.dylib`julia_banner_42295 at version.jl:291
    frame #16: 0x00000001178d44a0 sys.dylib`jfptr_banner_42296 + 12
    frame #17: 0x0000000101121e54 libjulia-internal.1.9.dylib`ijl_apply_generic [inlined] _jl_invoke(F=0x0000000118068000, args=0x000000016f3b40e0, nargs=1, mfunc=0x00000001188d8620, world=<unavail
able>) at gf.c:0 [opt]
    frame #18: 0x0000000101121dec libjulia-internal.1.9.dylib`ijl_apply_generic(F=0x0000000118068000, args=0x000000016f3b40e0, nargs=<unavailable>) at gf.c:2574:12 [opt]
    frame #19: 0x0000000117699668 sys.dylib`julia_YY.961_33297 at client.jl:407
    frame #20: 0x0000000117699afc sys.dylib`jfptr_YY.961_33298 + 12
    frame #21: 0x0000000101121e54 libjulia-internal.1.9.dylib`ijl_apply_generic [inlined] _jl_invoke(F=0x0000000108abc340, args=0x000000016f3b44b8, nargs=1, mfunc=0x000000011952ea30, world=<unavail
able>) at gf.c:0 [opt]
    frame #22: 0x0000000101121dec libjulia-internal.1.9.dylib`ijl_apply_generic(F=0x0000000108abc340, args=0x000000016f3b44b8, nargs=<unavailable>) at gf.c:2574:12 [opt]
    frame #23: 0x000000010112eff8 libjulia-internal.1.9.dylib`jl_f__call_latest [inlined] jl_apply(args=<unavailable>, nargs=2) at julia.h:1840:12 [opt]
    frame #24: 0x000000010112efe8 libjulia-internal.1.9.dylib`jl_f__call_latest(F=<unavailable>, args=<unavailable>, nargs=2) at builtins.c:774:23 [opt]
    frame #25: 0x00000001172cfae8 sys.dylib`julia_run_main_repl_28961 at essentials.jl:796
    frame #26: 0x00000001172d7444 sys.dylib`julia_exec_options_37465 at client.jl:318
    frame #27: 0x00000001172d79c0 sys.dylib`julia__start_33771 at client.jl:518
    frame #28: 0x00000001172d7ab0 sys.dylib`jfptr__start_33772 + 8
    frame #29: 0x0000000101121e54 libjulia-internal.1.9.dylib`ijl_apply_generic [inlined] _jl_invoke(F=0x0000000117c1ade0, args=0x000000016f3b6668, nargs=0, mfunc=0x0000000117c1ac20, world=<unavail
able>) at gf.c:0 [opt]
    frame #30: 0x0000000101121dec libjulia-internal.1.9.dylib`ijl_apply_generic(F=0x0000000117c1ade0, args=0x000000016f3b6668, nargs=<unavailable>) at gf.c:2574:12 [opt]
    frame #31: 0x000000010117d4c8 libjulia-internal.1.9.dylib`true_main [inlined] jl_apply(args=0x000000016f3b6660, nargs=1) at julia.h:1840:12 [opt]
    frame #32: 0x000000010117d4b4 libjulia-internal.1.9.dylib`true_main(argc=<unavailable>, argv=<unavailable>) at jlapi.c:566:13 [opt]
    frame #33: 0x000000010117d3c0 libjulia-internal.1.9.dylib`jl_repl_entrypoint(argc=<unavailable>, argv=<unavailable>) at jlapi.c:710:15 [opt]
    frame #34: 0x0000000100a4bf6c julia`main(argc=<unavailable>, argv=<unavailable>) at loader_exe.c:59:15 [opt]
    frame #35: 0x0000000100afd088 dyld`start + 516
  thread #2
    frame #0: 0x0000000188452c40 libsystem_kernel.dylib`kevent + 8
    frame #1: 0x000000010117eff0 libjulia-internal.1.9.dylib`signal_listener(arg=<unavailable>) at signals-unix.c:721:27 [opt]
    frame #2: 0x000000018848a26c libsystem_pthread.dylib`_pthread_start + 148
  thread #3
    frame #0: 0x0000000188450290 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x000000018848a83c libsystem_pthread.dylib`_pthread_cond_wait + 1236
    frame #2: 0x00000001011e5374 libjulia-internal.1.9.dylib`uv_cond_wait + 32
    frame #3: 0x0000000101169624 libjulia-internal.1.9.dylib`ijl_task_get_next(trypoptask=0x0000000118bce9e0, q=0x0000000108a8c050, checkempty=0x0000000119608f10) at partr.c:416:17 [opt]
    frame #4: 0x0000000117432008 sys.dylib`julia_poptask_25670 at task.jl:935
    frame #5: 0x0000000117432118 sys.dylib`julia_wait_47901 at task.jl:944
    frame #6: 0x00000001173823e0 sys.dylib`julia_wait_47885 at condition.jl:124
    frame #7: 0x0000000117274f5c sys.dylib`julia_lock_35711 at remotecall.jl:281
    frame #8: 0x0000000117279660 sys.dylib`julia_YY.137_54579 at condition.jl:78
    frame #9: 0x0000000117279680 sys.dylib`jfptr_YY.137_54580 + 8
    frame #10: 0x0000000101121e54 libjulia-internal.1.9.dylib`ijl_apply_generic [inlined] _jl_invoke(F=0x0000000118564cd0, args=0x00000001089981d8, nargs=0, mfunc=0x0000000118564b10, world=<unavail
able>) at gf.c:0 [opt]
    frame #11: 0x0000000101121dec libjulia-internal.1.9.dylib`ijl_apply_generic(F=0x0000000118564cd0, args=0x00000001089981d8, nargs=<unavailable>) at gf.c:2574:12 [opt]
    frame #12: 0x0000000101140c40 libjulia-internal.1.9.dylib`start_task [inlined] jl_apply(args=0x00000001089981d0, nargs=1) at julia.h:1840:12 [opt]
    frame #13: 0x0000000101140c34 libjulia-internal.1.9.dylib`start_task at task.c:932:19 [opt]
```

It appears that launching the `tput` process takes some kind of lock that other tasks get into a deadlock situation with, but its unclear to me what precisely the lock is.  On my machine, this occurs roughly 10% of the time, I'd say.  Hitting `CTRL-C` when the process is locked causes the lock to be broken, and normal execution continues (without any indication that Julia received a signal, and properly colored):

```
$ julia
^C               _                                                                                                
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.291 (2022-03-30)
 _/ |\__'_|_|_|\__'_|  |  Commit 3f23c457da (28 days old master)
|__/                   |

julia>
```

When hung, I see that there is a zombie `tput` process in `htop`, but this makes sense, as `julia` is locked up, waiting but never reaping that child process.

**Comment by vtjnash** [comment]
There was a kernel bug, where a child process that exited at the wrong time (usually too fast) would fail to notify the parent of completion. Apple has reported it fixed to me, and we have also changed libuv to use a slightly different way of waiting for completion (so it should work now on old kernels too).

**Comment by staticfloat** [comment]
I can confirm that on macOS 12.6 this is not fixed yet.  @vtjnash do you know which macOS kernel supposedly has this fixed?

**Comment by vtjnash** [comment]
12.3 beta 1, but we also hopefully removed the problem code from libuv. I have been waiting for apple to release the updated open source code for xnu to try to better confirm it

**Comment by giordano** [comment]
> I have been waiting for apple to release the updated open source code for xnu to try to better confirm it

https://github.com/apple-oss-distributions/xnu has the source code up to xnu-8792.61.2, which according to https://opensource.apple.com/releases/ corresponds to macOS 13.1. Source code of previous versions is also available
