### ISSUE TITLE
Running GLMakie with --compiled-modules=no leads to segfault

### ISSUE THREAD

**Issue by kbarros** [JuliaLang/julia#48844]
If Julia is launched with the `--compiled-modules=no` option, then the following code will segfault:

```julia
using GLMakie
fig = Figure()  # <-- sometimes crashes here
ax = Axis(fig[1,1])
lines!(ax, 1:10, (1:10) .^ 2)
save("test.png", fig)
```

Output:
```
[3892] signal (10.1): Bus error: 10
in expression starting at none:0
jl_system_image_data at /Users/kbarros/.julia/juliaup/julia-1.9.0-beta4+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
Allocations: 144650618 (Pool: 144563243; Big: 87375); GC: 175
```

This code runs fine with when compiled modules are enabled (i.e., default Julia).

Tested on `GLMakie v0.8.2`. The problem appears on multiple machines, including M1 Apple, as well as on the JuliaHub build machines. Another segfault output is given by the JuliaHub log here: https://juliahub.com/ui/Code/docs/Sunny/atBCQ/0.4.1.log

My local machine is this:
```
julia> versioninfo()
Julia Version 1.9.0-beta4
Commit b75ddb787ff (2023-02-07 21:53 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores
```

Thanks in advance.

**Comment by timholy** [comment]
Wow that takes a long time to run. I have tried replicating it twice, on `master` with #48882 (which should be irrelevant), and failed to obtain the crash. So I'd ask whether there's any chance you can supply any additional detail?
- does it always crash? (not sure if "sometimes" means "sometimes this spot, sometimes at the end of the sequence of commands", or if it means "sometimes it crashes, sometimes it doesn't")
- can you replicate it on nightly? or (in a dream world) a debug build?
- have you tried Linux as well as macOS?
- any insight about whether it's M1-dependent?
- was your `~/.julia/compiled/v1.9` folder empty before you tried that?
- are you running this from the REPL or a script?

**Comment by vchuravy** [comment]
Also what happens on `--compiled-modules=no --pgkimages=no`?

I am wondering if we run into the case of the sysimage not being loaded fully, but we are still using compiled code from pkgimages, that contain relocations to sysimage functions. I don't think I implemented any special support for `--compiled-modules=no` & pkgimages so we might hit a slightly different code-path than sysimage loading.

Or more precisely @JeffBezanson what should the semantics of `--compiled-modules=no` and pkgimages be?

**Comment by timholy** [comment]
I've now tried this in the REPL four times on julia1.9.0-beta4, and I still can't replicate it. I did it twice with an empty `compiled/v1.9` directory, and twice where I first precompiled GLMakie but then ran with `--compiled-modules=no` (just in case it's mistakenly reading from cache files). At no point did it cause any kind of error.

Until more info comes to light, I'd propose this should not be blocking for the release of 1.9.

**Comment by kbarros** [comment]
> does it always crash? (not sure if "sometimes" means "sometimes this spot, sometimes at the end of the sequence of commands", or if it means "sometimes it crashes, sometimes it doesn't")

Yes, it's crashing reliably for me, currently on Mac.

> can you replicate it on nightly? or (in a dream world) a debug build?

I have just reproduced on latest nightly:
```
Julia Version 1.10.0-DEV.694
Commit ef077475456 (2023-03-03 19:15 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores
```

> have you tried Linux as well as macOS?
> any insight about whether it's M1-dependent?

This was first discovered because JuliaHub doc builds were crashing. The JuliaHub log is here:
https://juliahub.com/ui/Code/docs/Sunny/atBCQ/0.4.1.log

Presumably JuliaHub servers are Linux, non-M1 machines, which would imply it's not M1-dependent. Let me try to reproduce on a local Linux machine and get back to you.

> was your ~/.julia/compiled/v1.9 folder empty before you tried that?

My `~/.julia/compiled/v1.10` was empty for the crash reported above, on nightly.

> are you running this from the REPL or a script?

I have observed crashes in both. Let me try Linux next.

**Comment by kbarros** [comment]
I also observe a crash on Linux x86_64 nightly

Detailed steps:
1. Verify that `~/.julia/compiled/v1.10` is not present at all. Neither was `~/.julia/environments/v1.10` for this test.
2. Download Julia nightly with `wget https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz`
3. Uncompress and launch with `./julia-778947fa02/bin/julia --compiled-modules=no`
4. Download GLMakie with `(@v1.10) pkg> add GLMakie`
5. From the REPL, execute `using GLMakie` (this works) and then `fig = Figure()` (this segfaults). The full crash output is listed below.

This machine is:
```
julia> versioninfo()
Julia Version 1.10.0-DEV.695
Commit 778947fa029 (2023-03-03 20:23 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 1 on 16 virtual cores
```

Crash output:
```
[5429] signal (11.2): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7f31e49401d0)
GLFramebuffer at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/glwindow.jl:62
#empty_screen#40 at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:245
empty_screen at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:203 [inlined]
singleton_screen at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:299
#Screen#47 at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:388
Screen at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:387
unknown function (ip: 0x7f3200b026c9)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
#getscreen#1013 at /home/kbarros/.julia/packages/Makie/gAmAB/src/display.jl:336
getscreen at /home/kbarros/.julia/packages/Makie/gAmAB/src/display.jl:324 [inlined]
#display#1007 at /home/kbarros/.julia/packages/Makie/gAmAB/src/display.jl:148
display at /home/kbarros/.julia/packages/Makie/gAmAB/src/display.jl:133
unknown function (ip: 0x7f3200b00782)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
jl_apply at /cache/build/default-amdci4-2/julialang/julia-master/src/julia.h:1878 [inlined]
jl_f__call_latest at /cache/build/default-amdci4-2/julialang/julia-master/src/builtins.c:778
#invokelatest#2 at ./essentials.jl:828 [inlined]
invokelatest at ./essentials.jl:825 [inlined]
print_response at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:299
#57 at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:281
jfptr_YY.57_61287.clone_1 at /home/kbarros/installs/julia-778947fa02/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
with_repl_linfo at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:551
jfptr_with_repl_linfo_61315.clone_1 at /home/kbarros/installs/julia-778947fa02/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
print_response at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:279
do_respond at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:893
jfptr_do_respond_61368.clone_1 at /home/kbarros/installs/julia-778947fa02/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
jl_apply at /cache/build/default-amdci4-2/julialang/julia-master/src/julia.h:1878 [inlined]
jl_f__call_latest at /cache/build/default-amdci4-2/julialang/julia-master/src/builtins.c:778
#invokelatest#2 at ./essentials.jl:828 [inlined]
invokelatest at ./essentials.jl:825 [inlined]
run_interface at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2648
jfptr_run_interface_60629.clone_1 at /home/kbarros/installs/julia-778947fa02/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
run_frontend at /cache/build/default-amdci4-2/julialang/julia-master/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1294
#62 at ./task.jl:514
jfptr_YY.62_61299.clone_1 at /home/kbarros/installs/julia-778947fa02/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2731 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-master/src/gf.c:2913
jl_apply at /cache/build/default-amdci4-2/julialang/julia-master/src/julia.h:1878 [inlined]
start_task at /cache/build/default-amdci4-2/julialang/julia-master/src/task.c:1093
Allocations: 139018865 (Pool: 138910170; Big: 108695); GC: 173
Segmentation fault (core dumped)
```

**Comment by kbarros** [comment]
> Also what happens on --compiled-modules=no --pgkimages=no?

I get this:
```
julia-778947fa02/bin/julia --compiled-modules=no --pgkimages=no
ERROR: unknown option `--pgkimages=no`
```
Perhaps a typo?

**Comment by giordano** [comment]
```
% julia +1.9 --help | grep images
 --pkgimages={yes*|no}
                            Enable or disable usage of native code caching in the form of pkgimages ($)
```

**Comment by kbarros** [comment]
Still crashing. This time GLMakie was already installed. Full inputs below:

```
./julia-778947fa02/bin/julia --compiled-modules=no --pkgimages=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0-DEV.695 (2023-03-03)
 _/ |\__'_|_|_|\__'_|  |  Commit 778947fa029 (0 days old master)
|__/                   |

(@v1.10) pkg> st
Status `~/.julia/environments/v1.10/Project.toml`
  [e9467ef8] GLMakie v0.8.2

julia> using GLMakie

julia> fig = Figure()

[8742] signal (11.2): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7f2e823920a0)
glGenFramebuffers at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/GLAbstraction/GLExtendedFunctions.jl:139 [inlined]
GLFramebuffer at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/glwindow.jl:61
#empty_screen#40 at /home/kbarros/.julia/packages/GLMakie/N16Fq/src/screen.jl:245
...
```

**Comment by kbarros** [comment]
Note: It might be important that `display` is implicitly getting called on `Figure()`?

**Comment by DilumAluthge** [comment]
On macOS x86_64 (Intel), I get `SIGBUS`.

Here are the steps I took to reproduce. First, open a new Bash session and run the following:
```bash
cd "$(mktemp -d)"
export JULIA_DEPOT_PATH="$(mktemp -d)"
unset JULIA_LOAD_PATH
unset JULIA_PKG_SERVER

curl -LO https://julialangnightlies-s3.julialang.org/bin/macos/x86_64/julia-latest-macos-x86_64.tar.gz
tar xzf julia-latest-macos-x86_64.tar.gz

# Open a Julia REPL:
./julia-0ec704e266/bin/julia --compiled-modules=no
```

Now, in the Julia REPL, run the following:
```julia
julia> versioninfo()

(v1.10) pkg> add GLMakie
(v1.10) pkg> precompile
(v1.10) pkg> st

julia> ENV["JULIA_DEBUG"] = "loading"
julia> using GLMakie
julia> fig = Figure()
julia> display(fig)
```

And here is the output that I received:

```
julia> using GLMakie
┌ Debug: Extension AdaptStaticArraysExt of Adapt loaded
└ @ Base loading.jl:1196
┌ Debug: Extension LogExpFunctionsChainRulesCoreExt of LogExpFunctions loaded
└ @ Base loading.jl:1196
┌ Debug: Extension SpecialFunctionsChainRulesCoreExt of SpecialFunctions loaded
└ @ Base loading.jl:1196
┌ Debug: Extension StatsFunsChainRulesCoreExt of StatsFuns loaded
└ @ Base loading.jl:1196
┌ Debug: Extension DistributionsChainRulesCoreExt of Distributions loaded
└ @ Base loading.jl:1196
┌ Debug: Extension StaticArraysExt of ConstructionBase loaded
└ @ Base loading.jl:1196
┌ Debug: Extension IntervalSetsExt of ConstructionBase loaded
└ @ Base loading.jl:1196

julia> fig = Figure()

[1413] signal (10.2): Bus error: 10
in expression starting at none:0
unknown function (ip: 0x12f5ede10)
Allocations: 139303816 (Pool: 139194503; Big: 109313); GC: 192
Bus error: 10
```

**Comment by timholy** [comment]
Can anyone replicate this with a debug source-build of Julia?

**Comment by alhirzel** [comment]
I was able to reproduce the issue on a debug build of `master`, x86-64, and I have a core dump.

**Comment by vchuravy** [comment]
I suspect

https://github.com/JuliaGL/ModernGL.jl/blob/404b9cd6812bed13ba26a3ace5a7ae43d97e1b88/src/functionloading.jl#L59-L64

is to blame...  We might be accidentally caching pointer values across sessions. But the code pattern there is very sketch. ModernGL should reload these pointers during `__init__`. @SimonDanisch

**Comment by vchuravy** [comment]
```
module PtrTest

const ptr = Ref{Ptr{Cvoid}}(reinterpret(Ptr{Cvoid}, 0xdeadbeefdeadbeef))

end # module PtrTest
```

```
vchuravy@odin ~/s/e/PtrTest (master)> julia --project --compiled-modules=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-beta4 (2023-02-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PtrTest

julia> PtrTest.ptr[]
Ptr{Nothing} @0x0000000000000000

vchuravy@odin ~/s/e/PtrTest (master)> julia --project --compiled-modules=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-beta4 (2023-02-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PtrTest

julia> PtrTest.ptr[]
Ptr{Nothing} @0xdeadbeefdeadbeef
```

This is consistent with 1.7

```
vchuravy@odin ~/s/e/PtrTest (master)> julia +1.7 --project --compiled-modules=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PtrTest

julia> PtrTest.ptr[]
Ptr{Nothing} @0xdeadbeefdeadbeef

ERROR: julia: invalid argument to --compiled-modules={yes|no} (ywa)
vchuravy@odin ~/s/e/PtrTest (master) [1]> julia +1.7 --project --compiled-modules=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PtrTest
[ Info: Precompiling PtrTest [d62965d4-a035-4647-819b-77608eb7fbbf]

julia> PtrTest.ptr[]
Ptr{Nothing} @0x0000000000000000
```

So my guess? The missing null-initialization of the Ref, causes there to be random garbage there, and with `--compiled-modules=yes` the serializer zero'ing out pointers saves your bacon.

**Comment by vchuravy** [comment]
I opened a PR to ModernGL.jl, please try to reproduce with that change.

**Comment by alhirzel** [comment]
@vchuravy - fix worked, nice job!

**Comment by kbarros** [comment]
Works for me to, thank you!
