### ISSUE TITLE
Promotion of Irrational{s} with Complex{Irrational{s}} gives StackOverflowError

### ISSUE THREAD

**Issue by jmbyrne** [JuliaLang/julia#51001]
![image](https://github.com/JuliaLang/julia/assets/86945518/7e206407-2268-47ed-b4bd-0b58f2a1e6bd)

The `promote_rule` with an `Irrational{s}` type and a `Complex{Irrational{s}}` type (where `s` is the same `Symbol`) gives a `StackOverflowError`. The intended type is probably `Complex{Irrational{s}}`, as demonstrated by swapping the arguments:

![image](https://github.com/JuliaLang/julia/assets/86945518/3ba7b80a-b789-499f-8413-b57ab63d1e40)

If the parameters are different (e.g. `Irrational{:ℯ}` with `Complex{Irrational{:π}}`), then there is no issue as it promotes to `ComplexF64`.

---
Julia version 1.9.2 installed on Windows 11 with the Julia installer https://julialang.org/downloads/

**Comment by Seelengrab** [comment]
A bit orthogonal, but please note that Julia is not a CAS - not everything is expected to preserve irrationals, or combinations thereof. This looks like it should be fixed though.

**Comment by jmb280cam** [comment]
I agree that since `Irrational` types are singleton types it would be very rare to actually come across this. However, it is possible, for instance `promote(π, complex(π, π))` causes the same error. Not sure why you'd use `complex(π, π)`, but there might be a good reason!

For a bit of added context, I was trying to promote every possible pair of numeric types to generate a diagram, but this was stopping it. Since you mentioned swapping the arguments, there is some more strange behaviour related to that, e.g.:
![image](https://github.com/JuliaLang/julia/assets/86945518/479f0027-812d-4ba3-8ad6-38b4bc39515a)

I don't know whether this is actually a problem, and if it is, whether it should be its own issue anyway. I'll let someone else be the judge of that.

**Comment by bvdmitri** [comment]
I think you are [supposed](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Promotion) to use `promote_type` instead, which uses the `promote_rule` under the hood but also ensures symmetry.

**Comment by jmb280cam** [comment]
You're right, I missed that. The original issue still stands though, that breaks with either `promote_type` or `promote_rule`.

**Comment by nsajko** [comment]
Faulty rule:

https://github.com/JuliaLang/julia/blob/25cbe006f3a610c204d8f2f67f1200a13a8ce349/base/irrationals.jl#L48-L48

xref #55866

**Comment by mbauman** [comment]
Is this the same as https://github.com/JuliaLang/julia/issues/13193?

**Comment by nsajko** [comment]
No, this one should be easier to fix.
