### ISSUE TITLE
Teach jl_create_native to emit ccallable aliases

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#52112]
Currently PackageCompiler contains a small init script (https://github.com/JuliaLang/PackageCompiler.jl/blob/master/src/julia_init.c) that needs to be compiled in C. For the next iteration of PackageCompiler, it would be nice to avoid this dependency, becuase it requires a working C compiler on the target platform.

Fortunately, we are now at the point where we can mostly write this in Julia.
With:
```
function c_main(argc::Cint, argv::Ptr{Ptr{Cchar}})
    argv = ccall(:uv_setup_args, Ptr{Ptr{Cchar}}, (Cint, Ptr{Ptr{Cchar}}), argc, argv)
    argcref = Ref{Cint}(argc)
    argvref = Ref{Ptr{Ptr{Cchar}}}(argv)
    ccall(:jl_parse_opts, Cvoid, (Ptr{Cint}, Ptr{Ptr{Ptr{Cchar}}}), argcref, argvref)
    ccall(:julia_init, Cvoid, (Cint,), 2)
    return ccall(:julia_trampoline, Cint, (Cint, Ptr{Ptr{Cchar}}), argc, argv)
end
```

We can compile this using:
```
mi = Base._methods_by_ftype(Tuple{typeof(c_main), Cint, Ptr{Ptr{Cchar}}}, 1, Base.get_world_counter())
params = Base.CodegenParams(;
    safepoint_on_entry=false,
    gcstack_arg=false,
    use_jlplt=false
)
native_code = ccall(:jl_create_native, Ptr{Cvoid},
            (Vector{MethodInstance}, Ptr{Cvoid}, Ptr{Base.CodegenParams}, Cint, Cint, Cint, Csize_t),
            [mi], C_NULL, Ref(params), 1, 1, 0, Base.get_world_counter())
ccall(:jl_dump_native, Cvoid, (Ptr{Cvoid}, Cstring, Cstring, Cstring, Cstring, Ptr{Cvoid}, Ptr{Cvoid}),
            native_code, "opt.bc.a", "unopt.bc.a", "opt.o.a", "opt.s", C_NULL, C_NULL)
```

and link it to the output of a regular sysimage build (--output-o) of the following script
```
#!/usr/bin/env -S julia --project=@scriptdir
function (@main)(ARGS)
    println("Hello world!")
end

@Base.ccallable function julia_trampoline(argc::Cint, argv::Ptr{Ptr{Cchar}})::Cint
    ARGS = String[unsafe_string(unsafe_load(argv, i)) for i in 1:argc]
    r = (@main)(ARGS)
    r === nothing && (r = Cint(0))
    return r::Cint
end
```

and obtain a fully standalone binary, with one small caveat. Currently,
there is no way to ask `jl_create_native` to create a c-callable alias
for a particular method instance. We do have the capability to codegen this,
as it is used by `@ccallable`, but that creates global state (which is probably
not a great idea either), but it is not exposed in jl_create_native. If it were,
we could entirely cut our dependency on the existence of a C compiler in Julia.

**Comment by vchuravy** [comment]
>  Currently, there is no way to ask jl_create_native create a c-callable alias for a particular method instance. We do have the capability to codegen this,

You sure? We do create those for system images and pkgimages. I fixed that up recently https://github.com/JuliaLang/julia/pull/51514

**Comment by Keno** [comment]
> You sure? We do create those for system images and pkgimages. I fixed that up recently #51514

I wrote this down from memory, since @gbaraldi wanted to try finishing it, but I was pretty sure that the ccallable stuff was happening using some global state during sysimg/pkgimage emission and was not accessible using the jl_create_native API. Maybe I'm wrong, in which case, this'll be easy to fix ;).

**Comment by vchuravy** [comment]
I think it's slower than it should be #51894, but it should work.

**Comment by gbaraldi** [comment]
So the way you tell `create_native` to do a ccallable is that you pass it the `ccallable` field of a method (It's an svec) instead of passing an MI. Your use case here will still have an issue because currently ccallables are allocating and that seems to be a bug and wouldn't be allowed in this use case. But assuming that is fixed, one can do something like
```julia

import Base: MethodInstance

Base.@ccallable function c_main(argc::Cint, argv::Ptr{Ptr{Cchar}})::Cint
    argv = ccall(:uv_setup_args, Ptr{Ptr{Cchar}}, (Cint, Ptr{Ptr{Cchar}}), argc, argv)
    argcref = Ref{Cint}(argc)
    argvref = Ref{Ptr{Ptr{Cchar}}}(argv)
    ccall(:jl_parse_opts, Cvoid, (Ptr{Cint}, Ptr{Ptr{Ptr{Cchar}}}), argcref, argvref)
    ccall(:julia_init, Cvoid, (Cint,), 2)
    return ccall(:julia_trampoline, Cint, (Cint, Ptr{Ptr{Cchar}}), argc, argv)
end
# ms = Base._methods_by_ftype(Tuple{typeof(c_main), Cint, Ptr{Ptr{Cchar}}}, 1, Base.get_world_counter())
# mi = Core.Compiler.specialize_method(ms[1])
mi = methods(c_main)[1].ccallable

params = Base.CodegenParams(;
    safepoint_on_entry=false,
    gcstack_arg=false,
    use_jlplt=false
)


native_code = ccall(:jl_create_native, Ptr{Cvoid},
            (Vector{Any}, Ptr{Cvoid}, Ptr{Base.CodegenParams}, Cint, Cint, Cint, Csize_t),
            [mi], C_NULL, Ref(params), 1, 1, 0, Base.get_world_counter())

mutable struct EmissionParams
    emit_metadata::Cint
end
em_params = EmissionParams(1)

            #jl_dump_native_impl(void *native_code,const char *bc_fname, const char *unopt_bc_fname, const char *obj_fname,const char *asm_fname,ios_t *z, ios_t *s,jl_emission_params_t *params)
ccall(:jl_dump_native, Cvoid, (Ptr{Cvoid} #=native_code=#, Cstring #=bcname=#, Cstring  #=unoptbcname=#, Cstring  #= objname =#, Cstring #=asmname=#,  Ptr{Cvoid}  #=z=#, Ptr{Cvoid}  #=s=#, Ptr{EmissionParams} #=em_params=#),
            native_code, "opt.bc.a", "unopt.bc.a", "opt.o.a", "opt.s", C_NULL, C_NULL, Ref(em_params))
```
Another thing is that currently ccallable assumes that metadata will be emitted
