### ISSUE TITLE
activate LLVM37

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#9336]
this is an umbrella issue for tracking known issues with switching to LLVM35 as default. please edit this post or add a comment below. close when someone edits `deps/Versions.make` to ~~`3.6.0`~~ `3.7.0`

current known issues:
 - [ ] requires editing deps/Versions.make - #14623
 - [x] #7910 ([upstream patch](http://reviews.llvm.org/D6961) committed to 3.7 -- only an issue on Mac)
 - [ ] figure out performance regression (perhaps only run passes once ~~(requires writing a `TargetMachine` wrapper and overloading `addPassesToEmitMC`)~~ (requires changes to LLVM to expose passes))
 - [x] requires leaving behind LLVM33
 - [x] would eliminate content from the "fixed in LLVM 3.5" issue label
 - [x] #8137
 - [x] #8999
 - [x] #9280
 - [x] #9339 ~~(LLVM36-only issue)~~
 - [x] #9967 (fixed in LLVM36)
 - [x] #10377
 - [x] #10394
 - [x] #11085 linalg/arnoldi test on win64
 - [x] #11083
 - [x] ~~#10806~~ (afaict, this is a non-fatal issue in valgrind. jwn)
 - [x] #11003 
 - [x] ~~#13106~~ (this issue is a non-fatal performance regression. jwn)
 - [x] re-disable FPO

related:
- [x] #7779 coverage flags are broken with LLVM 3.5 on master 

@Keno

**Comment by ihnorton** [comment]
We should probably also take a look at performance metrics before flipping the switch. On my llvm-svn build, building the sys image (`touch base/sysimg.jl && time make -j2`) takes 4 minutes as compared to 2 minutes on LLVM3.3

**Comment by Keno** [comment]
That's because we run all the passes twice ;). But yes, that's a TODO item.

**Comment by ihnorton** [comment]
Derp. Well that makes sense then!

**Comment by vtjnash** [comment]
@Keno is that just applicable building the sysimg?

**Comment by Keno** [comment]
No, MCJIT does not yet have a way to alter the passes that it runs as far as I'm aware (though I was promised this would be possible in the near future), this means that e.g. our SIMD lowering pass would not be run if we didn't run all the passes ourselves (I suppose we could just set MCJIT's opt level to None, but I think that actually also disabled optimizations in the backend).

**Comment by vtjnash** [comment]
ah, i see that now. It appears we would need to create a TargetMachine wrapper class and overload `addPassesToEmitMC` in order to set the passes list. Not very direct, but also not very difficult.

**Comment by Keno** [comment]
Yes, that would probably work.

**Comment by vtjnash** [comment]
so if someone patches that, and we merge your patches for #7910 into the JuliaLang/llvm branch, i think we might be ready to switch to llvm35

**Comment by Keno** [comment]
Sounds right to me.

**Comment by tkelman** [comment]
Should we be shooting for 3.6.0 now that it's out? http://llvm.org/releases/

**Comment by vtjnash** [comment]
it looks like we could create a micro-branch to trivially address the remaining item on the above list and make the switch

**Comment by tkelman** [comment]
Anybody else see a failure on the complex test with 3.6.0?
```
exception on 3: ERROR: LoadError: test failed: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in expression: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in error at ./error.jl:19
 in default_handler at ./test.jl:27
 in do_test at ./test.jl:50
 in runtests at /home/tkelman/Julia/julia/test/testdefs.jl:79
 in anonymous at ./multi.jl:833
 in run_work_thunk at ./multi.jl:584
 in anonymous at ./multi.jl:833
while loading complex.jl, in expression starting on line 7
        From worker 2:       * broadcast            in  27.41 seconds
ERROR: LoadError: LoadError: test failed: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in expression: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in anonymous at ./task.jl:1370
while loading complex.jl, in expression starting on line 7
while loading /home/tkelman/Julia/julia/test/runtests.jl, in expression starting on line 3

        From worker 3:       * complex             make[1]: *** [all] Error 1
make: *** [test] Error 2

tkelman@ygdesk:~/Julia/julia$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3637 (2015-03-01 18:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 74c71fb* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> versioninfo()
Julia Version 0.4.0-dev+3637
Commit 74c71fb* (2015-03-01 18:30 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY PENRYN)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0

julia> sqrt(complex(0.0,-0.0))
0.0 + 0.0im

julia> isequal(sqrt(complex(0.0,-0.0)), complex(0.0,-0.0))
false
```

**Comment by simonbyrne** [comment]
Hmm, that shouldn't occur: the relevant lines in `sqrt` are:
```julia
x, y = reim(z)
if x==y==0
    return Complex(zero(x),y)
end
```
That result isn't a valid (IEEE754) transformation. A similar issue occurred in https://github.com/JuliaLang/julia/pull/9880#issuecomment-72247261.

**Comment by Keno** [comment]
Unfortunately, even after playing around with the pass order, I'm still seeing significant performance regressions in compile time (about 2x during the linalg testsuite, which is the most codegen heavy we have). We should do some profiling to see if this can't be improved.

**Comment by tkelman** [comment]
Once everything is finally fixed and we make the switch, we should remember to go looking for places in the code or tests with LLVM-related todo's.

**Comment by ihnorton** [comment]
CI failure in #10741 points out that we are going to need a newer build toolchain on travis because LLVM now requires gcc > 4.7, whereas Travis is still on 4.6 (https://github.com/travis-ci/travis-ci/issues/1379).

**Comment by vtjnash** [comment]
since we are still targeting msvc, i think we'll need to make sure our code is compatible with both

**Comment by tkelman** [comment]
Both what? We can poke Elliot to help update the ppa for llvm when needed, we can probably use the toolchain ppa (which should have 4.8, 4.9, etc) to build there.

**Comment by ihnorton** [comment]
Presumably both gcc and vc++... On that note, LLVM now [requires](http://llvm.org/docs/GettingStartedVS.html#software) VS2013+, which [supports](https://msdn.microsoft.com/en-us/library/hh567368.aspx) a decent subset of C++11.

**Comment by ihnorton** [comment]
What is the status of pass control/ordering issue?

Do we still need [this](https://github.com/JuliaLang/julia/issues/9336#issuecomment-72148381): "It appears we would need to create a TargetMachine wrapper class and overload addPassesToEmitMC in order to set the passes list. Not very direct, but also not very difficult."

Or did someone write that already?

**Comment by vtjnash** [comment]
that's item 3 above

> Only run passes once (requires writing a TargetMachine wrapper and overloading addPassesToEmitMC) (requires changes to LLVM to expose passes)

also, I realized the proposed wrapper class was impossible to create in C++

**Comment by ihnorton** [comment]
> I realized the proposed wrapper class was impossible to create in C++

Mind to clarify: does "impossible" refer to the fact that the real target implementations we need (`X86Target`, etc.) are all themselves derived from llvm::LLVMTargetMachine (via llvm::TargetMachine)?

> requires changes to LLVM to expose passes

Are you aware of any existing patches?

One simple idea is to add `EngineBuilder::setMCJITPassList(std::vector<Pass*>)` and then have MCJIT add all of the passes each time `emitObject` is called, before [calling `addPassesToEmitMC`](https://github.com/llvm-mirror/llvm/blob/302f000bf4fdf4346af58f73e2cf300bbb453a1c/lib/ExecutionEngine/MCJIT/MCJIT.cpp#L158-L159).

**Comment by vtjnash** [comment]
> Are you aware of any existing patches?

the existing mechanisms are deprecated, although the replacement is not yet written

> One simple idea is to add EngineBuilder::setMCJITPassList(std::vector<Pass*>) and then have MCJIT add all of the passes each time emitObject is called, before calling addPassesToEmitMC.

yeah, that's the right part of the code that we would want to modify in a custom build of llvm to allow us to put our own pass list there instead of the pass list from the TargetMachine

**Comment by tkelman** [comment]
is any of the new orcjit stuff in 3.6.0 and/or useful for us?

**Comment by ihnorton** [comment]
OrcJIT didn't make it into 3.6 AFAICT.

**Comment by Mike43110** [comment]
http://llvm.1065342.n5.nabble.com/Re-Modify-a-module-at-runtime-in-MCJIT-td79638.html

I saw this:
"The Orc layers provide a "removeModuleSet" method that enables you to delete the JIT state associated with a particular module (or set of modules) that you have added. This saves you from manually managing multiple MCJIT interfaces."

As something potentially useful out of OrcJIT.

**Comment by Keno** [comment]
Yes, Orc is quite good and also organizes some of the messy code we have in julia to deal with MCJIT quirks. I suspect we might move to it in the near future.

**Comment by vtjnash** [comment]
> figure out performance regression compared to JIT

a quick profiling run on OS X with llvm3.6.0+Release+Asserts seems to indicate the following time losses:
 - `addPassesToEmitMC` (~8% of total function emission time)
 - `~PassManagerImpl` (~3% of total function emission time)
 - `FPPassManager::doInitialization` (~1.5% of total emission time)
 - `FPPassManager::doFinalization` (~6% of total emission time)
 - `PMTopLevelManager::findAnalysisPass` / `PMTopLevelManager::findAnalysisPassInto` (~9% of total emission time, in Assertions build only)
 - `FPM->run(f)` (adds ~40% to total emission time, mostly in instruction combining, but this time is not being double-counted, since those passes don't rerun during emitObject)

some other info:
 - running the AsmPrinter ~5%
 - physical register allocation (greedy) ~5%
 - live variable analysis run ~2%
 - machine scheduling (processor pipeline optimization) ~5%
 - lowering llvm opcodes to sdnode opcodes ~20%
   - SDNode combination optimizations ~5%
 - relocation ~pretty negligable%

* totals are given as a % of time spent in `MCJIT::emitObject` for a call to `./julia invalid_arg`

**Comment by garrison** [comment]
#10806 might also be good to have on this list, though it is unclear how serious of an issue it is.

**Comment by mlubin** [comment]
@tkelman mentioned that codegen bugs in LLVM33 were holding up some of the important array changes. Could we just switch to LLVM36 and carry along patches as we already do now for LLVM33?

**Comment by tkelman** [comment]
Specifically I was referring to https://github.com/JuliaLang/julia/pull/10525#issuecomment-100420099

We don't have proposed patches yet for all of the not-yet-checked boxes in here, but I would be in favor of @Keno trying to bring his patches into the repo here to at least temporarily solve any problems that we know the solution to.

**Comment by ViralBShah** [comment]
+1 to that.

**Comment by garrison** [comment]
LLVM `3.6.1` [has been released](http://llvm.org/releases/download.html#3.6.1).

**Comment by yuyichao** [comment]
I've justed tested LLVM 3.6.1 yesterday and it passes all the julia tests. =)

**Comment by vchuravy** [comment]
So there is one week left to nominate patches for `3.6.2`

https://groups.google.com/d/msg/llvm-dev/wEnVJk3akns/IlgEvBGOpp8J

**Comment by tkelman** [comment]
Re: exposing passes, looks like the LLILC folks are doing some useful work on top of ORC that we might be able to use if it gets upstreamed (or just carry locally, it's also MIT-licensed)? https://github.com/dotnet/llilc/pull/685

**Comment by tkelman** [comment]
3.7.0 is out, I'm guessing there's no really strong reason to try too hard to make 3.6 work other than for distro packagers.

**Comment by vtjnash** [comment]
please only add blocking issues to the list at the top list, not performance regressions and such

**Comment by tkelman** [comment]
Isn't the massive codegen performance regression the last blocking issue?

**Comment by vtjnash** [comment]
yes, but that is already in the list above, and is a regression in codegen itself, not in the generated code

**Comment by Keno** [comment]
Between fast-isel, my most recent commit and an LLVM patch which I'll submit upstream tomorrow, I've gotten the bootstrap building time on llvm-svn down from 10 min to 2min5s, with 3.3 taking about 1m45s. Need to do some more extensive benchmarking to see what the remaining regressions are.

**Comment by tkelman** [comment]
How big of an impact is the patch? Will we be waiting for 3.8, or can we carry the patch locally against 3.7.0?

**Comment by Keno** [comment]
`11 lines`

**Comment by timholy** [comment]
The best patches are small.

**Comment by StefanKarpinski** [comment]
I think that means it's time to switch master to our own form of LLVM with that patch on it. What do you say, @Keno?

**Comment by StefanKarpinski** [comment]
s/form/fork/

**Comment by tkelman** [comment]
A patch file that applies to a release tarball of llvm would be preferable to relying on a git fork

**Comment by StefanKarpinski** [comment]
Uh, why? We need to track LLVM SVN without being subject to random breakage whenever they decide to change APIs. Maintaining our own fork of LLVM that tracks upstream while rebasing a few patches and fixing breakage periodically seems far easier than anything else. This is literally what git rebase is for.

**Comment by tkelman** [comment]
Do we actually need to track llvm svn on master? Picking an arbitrary unsupported development version of such a large dependency to pin to makes it impossible for distros to package julia. We would also need to leave these branches in place permanently as is, otherwise building past points in julia master history will not be reproducible for future bisecting.

If these patches are small we can nominate them for being backported to llvm 3.7.1. If we can structure our requirements as patch files relative to release versions of llvm rather than our own diverging fork that is only relevant to us, it makes for much better release stability discipline on our part.

**Comment by nalimilan** [comment]
I agree with @tkelman. If we want to continue providing nightly packages, better stick to a stable release (possibly with a few patches if needed). I can't impose on the Fedora infrastructure to rebuild a custom LLVM fork everyday with Julia.

**Comment by StefanKarpinski** [comment]
Our first priority needs to be making it less impossible to use crucial projects like Cxx, Gallium and the threading branch – all of which need a fairly current version of LLVM. At this point, it really needs to be possible use all of those with a vanilla master version of Julia. Otherwise these projects are never going to get the kind of testing and development that they need to become widely usable. As soon as there's a release of LLVM that we can support all of those, we can use that. This might happen with LLVM 3.9, which should be out by the time Julia 0.5 is ready.

Regarding distros, we can maintain compatibility with whatever versions of LLVM they are willing to ship. However, the current policy of forcing programming languages to use whatever random version of LLVM they happen to package essentially guarantees that things are going to be broken and shitty. We have no control over that policy, but I refuse to let distro policies act as a boat anchor that slows down all of Julia development any more than it already has.

**Comment by tkelman** [comment]
@StefanKarpinski I don't know if you're aware but there has been a fair amount of effort by @staticfloat to set up nightly buildbots for using llvm svn and to build nightlies with the cxx.jl build configuration. Those have never built successfully. We need to fix that first before imposing that level of brokenness and difficulty in building on master.

This isn't just about distros, it's also about not getting in the business of indefinitely maintaining our own custom fork of llvm. We need to get things upstreamed and use upstream's release numbering as some indication that things have been tested and will remain stable within that release series.

**Comment by StefanKarpinski** [comment]
Yes, of course, getting things working is necessary. I also guarantee you the fastest way to get things fixed is to switch Julia master over to using LLVM SVN.

And yes, of course we need to upstream patches to LLVM. But we need to do that either way, so it's irrelevant to this debate. *Waiting* for things to get upstreamed before using them is *killing* the progress of this project. It needs to stop now. If we keep Julia master on a released version of LLVM that means the earliest we can switch to a newer LLVM is 3.7.1, which *might* happen in November. But the patch might not make it into the 3.7.1, which means that the earliest we can update LLVM is February. Which is when Julia 0.5 is due. Even if LLVM 3.8 is released before Julia 0.5, it will be too risky to update LLVM that late in the release cycle, which would mean that Julia 0.5 would be released **still using LLVM 3.3**. That is totally unacceptable – LLVM 3.3 will be almost three years old at that point and being stuck on it is completely blocking crucial advances to the project.

I'm sorry, there's no other choice here: we need to start getting people using a newer version of LLVM, which requires Julia master using a forked copy of LLVM SVN for a while.

**Comment by ihnorton** [comment]
> getting in the business of indefinitely maintaining our own custom fork of llvm.

Is there any serious LLVM user who doesn't maintain their own fork? We can't force upstream to take patches on any specific timeframe. If we have to maintain a fork in order to push things forward, then so be it. I'm happy to volunteer to help maintain the fork if it means that we can rid ourselves of the current morass of ifdefs, get some semblance of sanity for building from LLVM trunk on Windows, and get more people pushing hard on debugging improvements.

(IMHO improved debugging is **by far the highest-leverage thing we can do right now** to increase the velocity of base development, on which so much else rests).

> cxx.jl build configuration. Those have never built successfully.

Is there an issue open about this?

**Comment by mlubin** [comment]
Wasn't the proposal to switch master to LLVM 3.7 with patches now?

**Comment by StefanKarpinski** [comment]
I don't see how using LLVM 3.7 with patches is better than a periodically updated fork. Since we do upstream fixes, tracking LLVM SVN means that the number of patches we need to maintain gets smaller as the changes get accepted upstream, and we get more testing with upstream changes for longer.

The model here should be that Julia master tracks LLVM master until we're ready for a release, at which point we can stabilize on the most recently released LLVM version, possibly with some patches.

**Comment by tkelman** [comment]
There's a cxx.jl issue about providing nightlies for ci with more details.

3.7 with patches is better IMO because it's a known reproducible quantity as opposed to switching to an ephemeral git branch model. Switching back and forth between a fork and releases sounds like extra work when we know julia releases will have to use releases of llvm. That's a ways off right now, but I don't want to get in the situation that you can't build 3-month old master to bisect an issue because the branchea have all changed.

For appveyor to continue working we also need to provide new windows llvm binaries for win32 and win64 every time llvm changes. If we get shared library llvm to work on windows (which it never has aiui) that might be fairly simple to provide via buildbot binaries. Otherwise we have to put static libs and headers in the nightly binaries or a separate deps upload, or manually build by hand repeatedly.

**Comment by ihnorton** [comment]
>  If we get shared library llvm to work on windows (which it never has aiui) that might be fairly simple to provide via buildbot binaries.

https://github.com/JuliaLang/llvm/pull/1 (builds fine, haven't run tests recently)

**Comment by staticfloat** [comment]
Some of the difficulties with building newer LLVM versions is just that they start to use kernel and compiler features that are newer than our ancient CentOS 5 buildbots!  Once 0.4 final is released, we can experiment with CentOS 6 buildbots to see if they work any better.  Note that this means people with glibc older than 2.12 will not be able to use our binaries, or build Julia from source.  That's probably fine, as I think most scientific clusters (the most difficult customers of all) have moved on to CentOS/RH 6.X already.  Not an assertion I can back up with hard data though.  :P

**Comment by tkelman** [comment]
Right now the llvm svn and cxx nightlies buildbots are separate jobs than the mainline release builders, so some of that centos 6 experimentation we could start now right?

**Comment by timholy** [comment]
If one is tracking the bleeding edge of LLVM, is it wise to use a wonderfully-solid-but-invariably-behind distro like CentOS?

**Comment by StefanKarpinski** [comment]
Whether using LLVM 3.7 with patches is viable or not largely depends on how many patches are needed. We need at least this 11-line patch to fix the code gen regression, which is quite small. But that's not all we want to support. I think that more modifications are needed to support threading, Cxx and Gallium. I may be wrong about that at this point – I haven't kept track of everything that ended up in LLVM 3.7.

Keeping a rebased patch set on an LLVM fork is a strictly more flexible model than the official release + patches model. We can emulate the release + patches model simply by setting the LLVM fork to the commit of that release. The bisect argument strikes me as specious for a couple of reasons: even if we track LLVM SVN more closely than every release, we would still only update it every month or so, and bisect would work fine within that range of commits; also, the LLVM build system handles incremental rebuilds just fine, so it wouldn't be hard to make sure that bisect works well even with frequently changing LLVM source, as long as we've got our Makefiles right.

**Comment by tkelman** [comment]
We need to build on an old system to make the binaries generic and possible to run anywhere newer. We rebuild gcc on the buildbots but have less control over kernel and glibc.

Everything I said about appveyor applies equally to the llvm package in the juliadeps ppa for travis too, we'll need to keep that frequently updated.

I don't think I explained the bisect issue clearly enough. If we start using an llvm fork on julia master, we need to treat the llvm branch like master or a release branch and not force push or rebase on it. Any new rebase should be a new branch, so previously-referred-to commits from past versions of julia can still be fetched.

**Comment by staticfloat** [comment]
As Tony says, I'm not too afraid of getting a build environment that works, I think the bigger impact will be raising the hard limit of what systems Julia 0.5 works on.  At our current release pace, it's entirely likely that every old curmudgeonly computer cluster out there will be compatible with `glibc 2.12` by the time 0.5 goes final (har har) but it's hard to tell without some kind of hard data.

I'm also in agreement with @tkelman; we will need to start treating our `llvm` fork like `openspecfun` or openlibm`, and ensuring that we don't accidentally rebase out old commits.  If that just means that we create a new branch every time we want to rebase stuff to make it prettier (thereby forcing `git` to keep that old somewhat-redundant history around), that's just what we'll have to do.

**Comment by ihnorton** [comment]
> I think the bigger impact will be raising the hard limit of what systems Julia 0.5 works on.

On that note, LLVM3.7 is the last release to support Windows XP as a runtime platform. (to be clear, I'm still in favor of bumping)

**Comment by vtjnash** [comment]
> an LLVM patch which I'll submit upstream tomorrow

@Keno can you post a link?

**Comment by vtjnash** [comment]
> Need to do some more extensive benchmarking to see what the remaining regressions are.

my profiling attempts earlier (https://github.com/JuliaLang/julia/issues/9336#issuecomment-96439083) indicated that another 10% loss comes from having Assertions turned on while having two FunctionPassManagers and another 20% loss from constructing a new FPM for every module

**Comment by Keno** [comment]
That's not my concern though. I suspect MCJIT still has a couple more `O(N^2)` case in the number of modules. Haven't submitted the patch yet, but it's just:
```
diff --git a/include/llvm/ExecutionEngine/SectionMemoryManager.h b/include/llvm/ExecutionEngine/SectionMemoryManager.h
index 0b0dcb0..446c887 100644
--- a/include/llvm/ExecutionEngine/SectionMemoryManager.h
+++ b/include/llvm/ExecutionEngine/SectionMemoryManager.h
@@ -84,6 +84,7 @@ public:
 
 private:
   struct MemoryGroup {
+      SmallVector<sys::MemoryBlock, 16> PendingMem;
       SmallVector<sys::MemoryBlock, 16> AllocatedMem;
       SmallVector<sys::MemoryBlock, 16> FreeMem;
       sys::MemoryBlock Near;
diff --git a/lib/ExecutionEngine/SectionMemoryManager.cpp b/lib/ExecutionEngine/SectionMemoryManager.cpp
index b22c6db..e319216 100644
--- a/lib/ExecutionEngine/SectionMemoryManager.cpp
+++ b/lib/ExecutionEngine/SectionMemoryManager.cpp
@@ -83,7 +83,7 @@ uint8_t *SectionMemoryManager::allocateSection(MemoryGroup &MemGroup,
   // Save this address as the basis for our next request
   MemGroup.Near = MB;
 
-  MemGroup.AllocatedMem.push_back(MB);
+  MemGroup.PendingMem.push_back(MB);
   Addr = (uintptr_t)MB.base();
   uintptr_t EndOfBlock = Addr + MB.size();
 
@@ -138,6 +138,13 @@ bool SectionMemoryManager::finalizeMemory(std::string *ErrMsg)
   // relocations) will get to the data cache but not to the instruction cache.
   invalidateInstructionCache();
 
+  // Now, remember that we have successfully applied the permissions to avoid
+  // having to apply them again.
+  CodeMem.AllocatedMem.append(CodeMem.PendingMem.begin(),CodeMem.PendingMem.end());
+  RODataMem.AllocatedMem.append(RODataMem.PendingMem.begin(),RODataMem.PendingMem.end());
+  CodeMem.PendingMem.clear();
+  RODataMem.PendingMem.clear();
+
   return false;
 }
 
@@ -145,7 +152,7 @@ std::error_code
 SectionMemoryManager::applyMemoryGroupPermissions(MemoryGroup &MemGroup,
                                                   unsigned Permissions) {
 
-  for (sys::MemoryBlock &MB : MemGroup.AllocatedMem)
+  for (sys::MemoryBlock &MB : MemGroup.PendingMem)
     if (std::error_code EC = sys::Memory::protectMappedMemory(MB, Permissions))
       return EC;
 
@@ -153,7 +160,7 @@ SectionMemoryManager::applyMemoryGroupPermissions(MemoryGroup &MemGroup,
 }
 
 void SectionMemoryManager::invalidateInstructionCache() {
-  for (sys::MemoryBlock &Block : CodeMem.AllocatedMem)
+  for (sys::MemoryBlock &Block : CodeMem.PendingMem)
     sys::Memory::InvalidateInstructionCache(Block.base(), Block.size());
 }
 ```

**Comment by vtjnash** [comment]
since the MCJIT MemoryManager can be easily replaced, can we copy that code into our local repo to avoid needing to patch llvm versions, but get the benefits immediately?

**Comment by Keno** [comment]
Yes. We can. Also, submitted upstream: http://reviews.llvm.org/D13156.

**Comment by Keno** [comment]
Landed as http://reviews.llvm.org/rL248981.

**Comment by StefanKarpinski** [comment]
:+1: that was a quick one :)

**Comment by Keno** [comment]
I have found another ~15% performance and also finally managed to get a decent profile here (wasn't easy - naive profiling shows 50% time spent in malloc with no backtrace because OS X system library doesn't have unwind info). I am hopeful that we can get rid of the pass initialization and destruction by doing tricks with ORCJIT (or even MCJIT). I'm also hopeful we might be able to squeeze out the suff in between Pass init/deinit and Isel, which from looking at it doesn't seem like it needs to take that long. For those wondering, overhead of just MCJIT is the stuff to the left of init/right of deinit.

<img width="1440" alt="screen shot 2015-10-08 at 1 13 25 am" src="https://cloud.githubusercontent.com/assets/1291671/10358441/51955586-6d5c-11e5-904d-fba0fe5119e5.png">

**Comment by Keno** [comment]
FWIW, I think I have now found all the O(N^2) in the number of modules. Current performance results are about a 1.5-2x regression on average on the test suite. One outlier is `unicode` at 2.5x

**Comment by Keno** [comment]
Good news: Was able to get rid of pass initialization overhead. Bad news: Didn't do much for performance numbers. Will do more benchmarking tomorrow.

**Comment by Keno** [comment]
Better news: I was benchmarking wrong and there actually does seem to be 14% improvement, which is in line with what I would have expected looking at the profile above.

Even better news: I realized I was accidentally still using LLVM_ASSERTIONS for llvm-svn. With the combination of those two we're down to 1.3-1.5x, which is starting to get close to where we can start talking.

**Comment by ScottPJones** [comment]
What exactly are you comparing, when you say you get a 2.5x regression on `unicode`?  The performance compiling all of `unicode.jl` on LLVM 3.3 vs svn?
Are there any particular things in the files included by `unicode.jl` that are harder for 3.8 to deal with?

**Comment by tkelman** [comment]
I'm getting a segfault on win64 with LLVM 3.7.0 in the linalg/triangular test, not much backtrace though:
```
#0  0x00000000778494ba in ntdll!RtlVirtualUnwind () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Can open a separate issue if anyone has any inkling which LLVM version we're going to want to end up using, either 3.7.0 + patches or a protected checkpoint branch of 3.8-devel.

**Comment by vtjnash** [comment]
@tkelman added to the tracker list above (re-disable FPO)

**Comment by tkelman** [comment]
bisected to 127ee86b89d, if that makes any sense

**Comment by tkelman** [comment]
> - [x] re-disable FPO

I'm getting a segfault at the very start of bootstrap now with LLVM 3.7.0 on both win32 and win64. Expected?

**Comment by vtjnash** [comment]
since that commit (40d46e7146dd5343c91d7df9df080cbd59e253c5) is still waiting for CI verification before it lands on master, I can confidently say that is not the problem.

**Comment by vtjnash** [comment]
fixed @tkelman's finding with 6ee80d3

**Comment by Keno** [comment]
Just to update my kf/modulecoalescing branch now uses the same or less memory than it does with 3.3. It also passes all tests, so we're getting pretty close. I'm currently running msan/asan/valgrind to make sure there aren't any subtle memory bugs remaining, as well as tracking down a small performance regression (couple %). Getting close.

**Comment by StefanKarpinski** [comment]
I don't think I've ever been so excited about a totally invisible change.

**Comment by timholy** [comment]
Once it's no longer necessary to go to build heroics to use Gallium, it won't be invisible for long :smile:.

**Comment by ViralBShah** [comment]
I say we pull the plug on 3.3 if it is only a small regression.

**Comment by tkelman** [comment]
It's not a small regression yet. LLVM 3.7.0 doesn't bootstrap at all on win32 with current master.

**Comment by Keno** [comment]
Yes, I'm the the process of cleaning up the patch. Should be ready very soon. I have verified that all the remaining performance regressions are essentially due to LLVM itself rather than the new vs old JIT. Some of those look solvable, but that should be done as part of a general effort to improve the performance, rather than ad hoc now (I don't think we have the infrastructure in place yet to adequately measure and track performance here yet - that's something we should work on).

**Comment by ViralBShah** [comment]
@jrevels has a performance measurement infrastructure coming sometime soon.

**Comment by Keno** [comment]
Yes that will be helpful for the track part. For the measure part I need to find a better way to get accurate profiles during codegen. I've been using callgrind for now, but I don't like the way it merges stack traces and it's also extremely slow, so I'm gonna try to find something better. In either case those things can wait until after the switch. Also just to summarize everything from above, the current state is as follows:
- Some compile time regressions yielding ~1.2-1.5x slow down on the test suite
- Memory regressions are fixed
- These numbers include a number of performance/memory patches I've committed upstream. I managed to get the most essential ones into 3.7.1, but not all of them and in particular not the memory ones. We should think about whether we want to backport those against 3.7.1 and apply them as part of the build process or switch to a custom branch (I don't have a strong opinion either way, but I know other people do - so just tell me what the preferred solution is and I'll make it so)

**Comment by tkelman** [comment]
I'd personally prefer patches against a release as the most repeatable option. Picking an arbitrary point in an upstream development branch history that will never be released exactly as is to base our build off of seems less than ideal. Otherwise there may be API changes between what we pick and the next release, so "LLVM38" would have conflicting meanings in our ifdefs - broken either on the "julia branch," or broken on upstream trunk.

**Comment by StefanKarpinski** [comment]
I'm fine with 3.7.1 + patches.

**Comment by ViralBShah** [comment]
I prefer 3.7.1 + patches too. I think it is ok to implement it as an llvm release branch + patches in our llvm repo, so that one doesn't have to frequently maintain patch files.

**Comment by timholy** [comment]
@Keno, if you're looking for more profiling tools: you're probably aware of this, but [SnoopCompile](https://github.com/timholy/SnoopCompile.jl) can measure the core-compiler (i.e., not including inference) cost on a per-function basis:

```jl
SnoopCompile.@snoop1 "/tmp/gadfly_compiles.csv" begin
    include(Pkg.dir("Gadfly", "test","runtests.jl"))
end

compiledata = readdlm("/tmp/gadfly_compiles.csv", '\t')
```
The first column contains the compile time in ns. This *should* (untested) run directly on master, or you can explore `snoop_on` as needed.

This doesn't give you a backtrace, so you won't know the reason for any regressions. But you could run this once with LLVM 3.3 and once with LLVM 3.7, look for cases that stick out, and then turn on some other profiler while testing those specific cases.

If you actually use Gadfly as a test case, you may want to remove the `include("precompile.jl")` during testing.

Not sure if this will really help, but wanted to make sure you knew about this option.

**Comment by tkelman** [comment]
Given issues like https://github.com/JuliaLang/julia/issues/13766, the fact that the llvm svn setup in the makefiles is custom and doesn't fit with the git-externals mechanism, I don't think we should use a git-based llvm by default if we have an equivalent way of avoiding it. The setup for llvm patches is already there and we have quite a few of them.

**Comment by ViralBShah** [comment]
Fair enough.

**Comment by nalimilan** [comment]
Going with release + patches will also make it easier to package the custom LLVM 3.7 version, so +1.

**Comment by Keno** [comment]
I've been testing this on windows and it crashes quite early. Either I'm going crazy or GCC is miscompiling LLVM. Could somebody else also take a look at the following assembly code:
```
  assert(getOperand(0)->getType() ==
                 cast<PointerType>(getOperand(1)->getType())->getElementType()
         && "Ptr must be a pointer to Val type!");
}
```
```
   │0x1a6b990 <llvm::StoreInst::AssertOK()+80>      mov    -0x18(%rbx),%rcx                                                       │
   │0x1a6b994 <llvm::StoreInst::AssertOK()+84>      callq  0x1bbf360 <llvm::cast_or_null<llvm::Value, llvm::Value>(llvm::Value*)> │
   │0x1a6b999 <llvm::StoreInst::AssertOK()+89>      mov    0x8(%rax),%rdx                                                         │
   │0x1a6b99d <llvm::StoreInst::AssertOK()+93>      mov    -0x30(%rbx),%rcx                                                       │
   │0x1a6b9a1 <llvm::StoreInst::AssertOK()+97>      callq  0x1bbf360 <llvm::cast_or_null<llvm::Value, llvm::Value>(llvm::Value*)> │
   │0x1a6b9a6 <llvm::StoreInst::AssertOK()+102>     mov    %rdx,%rcx                                                              │
   │0x1a6b9a9 <llvm::StoreInst::AssertOK()+105>     mov    0x8(%rax),%rsi                                                         │
  >│0x1a6b9ad <llvm::StoreInst::AssertOK()+109>     callq  0x1c60420 <llvm::cast<llvm::PointerType, llvm::Type>(llvm::Type*)>     │
   │0x1a6b9b2 <llvm::StoreInst::AssertOK()+114>     mov    0x10(%rax),%rax                                                        │
   │0x1a6b9b6 <llvm::StoreInst::AssertOK()+118>     cmp    (%rax),%rsi
```
I think it may be incorrectly assuming that `$rdx` is preserved over the call at offset `+97`. Does that sound like a plausible analysis?

**Comment by yuyichao** [comment]
Maybe stupid question but maybe check if the register value actually changes (or if the function called actually changes it?) (Can the compiler use a slightly different convension for a static function?)

**Comment by Keno** [comment]
Yes, the register value changes and in particular, it changes from the value of `getOperand(1)->getType()` to junk.

**Comment by yuyichao** [comment]
That's sounds like a bug for me (although I only have a few months of experience with calling convensions....)

It's strange though because it is loading what was in `%rdx` before `+97` into `%rsi` right after moving the junk value into `%rcx`...

**Comment by Keno** [comment]
Well, remember that this is win64 calling convention so `%rcx` is actually the first argument. I think if `%rdx` was preserved everything would work out just fine. Also `%rax` is the return value, so it's actually a different value now.

**Comment by Keno** [comment]
Here's the post-reload RTL: https://gist.github.com/anonymous/749e6e3e903e39bc37cf

I think that still looks fine so the problem gets introduced somewhere later. In particular it is noteworthy that the mov into rsi gets placed before the second call to cast_or_null.

**Comment by Keno** [comment]
This bug is extremely fragile. Doing any of a dozen things (e.g. deleting unrelated functions) trying to reduce it makes it go just away.

**Comment by yuyichao** [comment]
As long as you can reproduce this with a single (cpp) file, it's probably fine to just use that in the bug report report to GCC?

**Comment by Keno** [comment]
Yeah, I will

**Comment by Keno** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68601. In the meantime I'll try my luck with clang. At least there I can fix things if they break

**Comment by tkelman** [comment]
May also be worth trying a cmake build rather than autotools, it's possible they pay closer attention to having flags right in cmake since autotools is now officially deprecated upstream.

**Comment by Keno** [comment]
Perhaps. I think for now I'll wait for GCC 5.3 and see if that fixes it. Also it seems like Clang works fine, so maybe we should just switch.

**Comment by tkelman** [comment]
Much easier said than done in terms of getting that working on the buildbots and ensuring binaries are compatible with winrpm packages. We could put cross-built llvm and clang up on opensuse without too much work, but using that would require switching the buildbots fron cygwin-cross to msys2 which went very poorly the last time we tested it.

**Comment by tkelman** [comment]
I guess we could build https://github.com/tpoechtrager/wclang for cygwin-to-mingw-clang cross right after building our own llvm and clang, but then we'd have to do a second or third stage rebuilding llvm with the just built clang.

**Comment by Keno** [comment]
The version of clang doesn't have to be the same as we're building. We can build it once.

**Comment by tkelman** [comment]
Once per machine where Julia needs to be built from source. Would rather minimize manual error-prone and time consuming steps of building toolchains, and use/create binary packages wherever we can. Cygwin has a build of clang and llvm but it's usually out of date.

**Comment by Keno** [comment]
There's prebuilt binaries also.

**Comment by tkelman** [comment]
those are built against msvc though, wouldn't we need clang built against mingw-w64? and those binaries don't include the llvm libraries (which would be needed for a cygwin-build cross compile driver) last I checked - we've asked before about including them but doesn't seem upstream cares about binaries of anything other than clang-cl.exe on windows.

**Comment by Keno** [comment]
They can be built against any compiler you want as long as you're using it only as a compiler.

**Comment by tkelman** [comment]
Using clang for the windows build should probably move to a separate issue at this point. What I don't think will work is building a cygwin cross compiler wrapper of wclang (so the buildbots will continue to work) against an msvc binary of llvm. I'll have to try it though.

**Comment by Keno** [comment]
Yes, you are probably right, but for a linux buildbot, you can just use the linux clang. Clang doesn't have different compilers based on the target triple.

**Comment by tkelman** [comment]
Right, which makes it not very useful as a cross compiler driver due to not handling the runtime headers and libraries of the host system, and wclang fixes that so we could use it in our build system for linux or cygwin cross.

**Comment by Keno** [comment]
What is needed that isn't fixed by `-target FOO -isysroot BAR`?

**Comment by tkelman** [comment]
I don't think -isysroot is enough to make windows.h and all the linker stubs for win32 dlls work? If it were that easy, wclang probably wouldn't need to exist? If you can get a clang cross build to work in our build system and all our deps with just those flags, I'd be pleasantly surprised.

**Comment by Keno** [comment]
I'm not sure. It was enough on msys2 to get clang running, but that's obviously different.

**Comment by Keno** [comment]
Update on the GCC issue for those not following. It's already a known bug, and is causing by compiling LLVM at -O2, julia at -O0 and not using LLVM shared libraries, so if we want to work around this issue we just have to avoid doing any of those three things.

**Comment by nalimilan** [comment]
Does using LLVM shared libraries cause any issue these days? I set `USE_LLVM_SHLIB=1` for RPM packages, and it seems to work fine.

**Comment by Keno** [comment]
Works fine on Mac/Linux, I think it still needs a patch on windows (which is the relevant platform for this problem).

**Comment by tkelman** [comment]
Can we try again to bump that patch and get it upstreamed by 3.8 or are we running out of time? We only build julia-release at `-O0` right? Using llvm shlibs would reduce a lot of size duplication in libjulia and libjulia-debug.

**Comment by Keno** [comment]
LLVM 3.8 is still wide open, but since autotools is being deprecated, we should probably check what the status is with CMake.

**Comment by vtjnash** [comment]
XP support will also be gone

**Comment by StefanKarpinski** [comment]
We can also switch to LLVM 3.7 on platforms where it's doable and keep using LLVM 3.4 on others. We need to pull the trigger on this (at least partially) soon – this is holding up so much progress.

**Comment by petercolberg** [comment]
Please see #14191, neither LLVM 3.4 (segfault) nor LLVM 3.7 (10 times slower) work on Linux x86.

Switching from 3.3 to 3.8 seems the only way to go for Linux x86.

**Comment by tkelman** [comment]
It should be noted that based on download statistics of the tarball binaries, Linux x86 is by far (1 or 2 orders of magnitude IIRC) the least used version of Julia out of the 5 platforms we build binaries for and test on CI. So a partial switch on just linux x86_64, and maybe mac, to start with might make sense. #13569 should allow us to build a newer LLVM on Linux Travis without having to package it in a PPA, as long as a first source build can go through within the time limit (from then on it'll be cached). Travis OSX will need to wait for packaging the newer LLVM as a bottle, either by staticfloat or homebrew proper (https://github.com/Homebrew/homebrew-versions/pull/955).
